/* opening.js — generated by ../build.sh from _evidence-parts.js and _opening-core.js. Edit those. */
(function () {
'use strict';
/* ---------------------------------------------------------------- palette */
const INK = '#1b1747', COBALT = '#2f52d9', PERI = '#8c97ff',
      VERM = '#f2603f', CREAM = '#fbedd2', GREEN = '#a6c64f';
const LOOP = 8;
const TAU = Math.PI * 2;

/* ------------------------------------------------------------ math & ease */
const clamp = (x, a = 0, b = 1) => x < a ? a : x > b ? b : x;
const lerp = (a, b, t) => a + (b - a) * t;
const inv = (a, b, x) => clamp((x - a) / (b - a));
const sstep = (a, b, x) => { const t = inv(a, b, x); return t * t * (3 - 2 * t); };
const eio = t => t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
const eout = t => 1 - Math.pow(1 - t, 3);
const ein = t => t * t * t;
const eback = t => { const c1 = 1.70158, c3 = c1 + 1; return 1 + c3 * Math.pow(t - 1, 3) + c1 * Math.pow(t - 1, 2); };
const spring = (t, f = 12, d = 6) => t < 0 ? 0 : Math.exp(-d * t) * Math.cos(f * t);
const bump = (a, b, c, x) => x < a || x > c ? 0 : x < b ? sstep(a, b, x) : 1 - sstep(b, c, x);

function mulberry32(a) {
  return function () {
    a |= 0; a = a + 0x6D2B79F5 | 0;
    let t = Math.imul(a ^ a >>> 15, 1 | a);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function hash2(x, y) {
  let h = (Math.imul(x | 0, 374761393) + Math.imul(y | 0, 668265263)) | 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}
function vnoise(x, y) {
  const xi = Math.floor(x), yi = Math.floor(y), xf = x - xi, yf = y - yi;
  const u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);
  const a = hash2(xi, yi), b = hash2(xi + 1, yi), c = hash2(xi, yi + 1), d = hash2(xi + 1, yi + 1);
  return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v;
}
function fbm(x, y) { let s = 0, a = .5, f = 1; for (let i = 0; i < 5; i++) { s += a * vnoise(x * f, y * f); f *= 2.03; a *= .5; } return s; }

/* 3D */
const v3 = (x, y, z) => [x, y, z];
const dot3 = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const sub3 = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const cross3 = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const norm3 = a => { const l = Math.hypot(a[0], a[1], a[2]) || 1; return [a[0] / l, a[1] / l, a[2] / l]; };
function rotX(a) { const c = Math.cos(a), s = Math.sin(a); return [1, 0, 0, 0, c, -s, 0, s, c]; }
function rotY(a) { const c = Math.cos(a), s = Math.sin(a); return [c, 0, s, 0, 1, 0, -s, 0, c]; }
function rotZ(a) { const c = Math.cos(a), s = Math.sin(a); return [c, -s, 0, s, c, 0, 0, 0, 1]; }
function mulM(A, B) {
  const r = new Array(9);
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++)
    r[i * 3 + j] = A[i * 3] * B[j] + A[i * 3 + 1] * B[3 + j] + A[i * 3 + 2] * B[6 + j];
  return r;
}
const mulMV = (M, v) => [M[0] * v[0] + M[1] * v[1] + M[2] * v[2], M[3] * v[0] + M[4] * v[1] + M[5] * v[2], M[6] * v[0] + M[7] * v[1] + M[8] * v[2]];

/* light: toward the upper left, a little toward the viewer (object space y up) */
const L3 = norm3([-0.48, 0.66, 0.58]);
const LS = (() => { const l = Math.hypot(-0.6, -0.8); return [-0.6 / l, -0.8 / l]; })(); // screen, y down

/* --------------------------------------------------------------- canvas */
const cv = document.getElementById('opening-canvas');
const ctx = cv.getContext('2d');
const scene = document.createElement('canvas');
const sctx = scene.getContext('2d');
let DPR = 1, U = 1, H = 1778, Wpx = 0, Hpx = 0;
let farTex = null, grains = [];
const TEX = { x0: -420, y0: -420, w: 1840, h: 0, fs: 1 };

/* --------------------------------------------------------------- helpers */
function poly(g, P) { g.beginPath(); g.moveTo(P[0][0], P[0][1]); for (let i = 1; i < P.length; i++) g.lineTo(P[i][0], P[i][1]); g.closePath(); }
function bboxOf(P) {
  let x0 = 1e9, y0 = 1e9, x1 = -1e9, y1 = -1e9;
  for (const p of P) { if (p[0] < x0) x0 = p[0]; if (p[0] > x1) x1 = p[0]; if (p[1] < y0) y0 = p[1]; if (p[1] > y1) y1 = p[1]; }
  return [x0, y0, x1, y1];
}
function hull2(pts) {
  const p = pts.slice().sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  const cr = (o, a, b) => (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);
  const lo = [], up = [];
  for (const q of p) { while (lo.length >= 2 && cr(lo[lo.length - 2], lo[lo.length - 1], q) <= 0) lo.pop(); lo.push(q); }
  for (let i = p.length - 1; i >= 0; i--) { const q = p[i]; while (up.length >= 2 && cr(up[up.length - 2], up[up.length - 1], q) <= 0) up.pop(); up.push(q); }
  up.pop(); lo.pop(); return lo.concat(up);
}
/* intersection of a ray from c at angle th with a convex polygon; returns point + outward normal */
function rayHull(c, th, Hp) {
  const dx = Math.cos(th), dy = Math.sin(th);
  let best = null;
  for (let i = 0; i < Hp.length; i++) {
    const a = Hp[i], b = Hp[(i + 1) % Hp.length];
    const ex = b[0] - a[0], ey = b[1] - a[1];
    const den = dx * ey - dy * ex; if (Math.abs(den) < 1e-9) continue;
    const ax = a[0] - c[0], ay = a[1] - c[1];
    const t = (ax * ey - ay * ex) / den, u = (ax * dy - ay * dx) / den;
    if (t > 0 && u >= -1e-6 && u <= 1 + 1e-6 && (!best || t > best.t)) {
      let nx = ey, ny = -ex; const l = Math.hypot(nx, ny); nx /= l; ny /= l;
      if (nx * dx + ny * dy < 0) { nx = -nx; ny = -ny; }
      best = { t, x: c[0] + dx * t, y: c[1] + dy * t, nx, ny };
    }
  }
  return best || { t: 0, x: c[0], y: c[1], nx: dx, ny: dy };
}

/* Halftone: dots on a fixed screen grid (units), radius from shade 0..1.
   shade is a number or a function (x, y) -> 0..1. Caller sets the clip. */
function halftone(g, bb, shade, color, cell, ang) {
  const ca = Math.cos(ang), sa = Math.sin(ang);
  let imin = 1e9, imax = -1e9, jmin = 1e9, jmax = -1e9;
  for (const [x, y] of [[bb[0], bb[1]], [bb[2], bb[1]], [bb[0], bb[3]], [bb[2], bb[3]]]) {
    const i = (x * ca + y * sa) / cell, j = (-x * sa + y * ca) / cell;
    if (i < imin) imin = i; if (i > imax) imax = i; if (j < jmin) jmin = j; if (j > jmax) jmax = j;
  }
  const fn = typeof shade === 'function';
  const k = cell * 0.66;
  g.beginPath();
  for (let j = Math.floor(jmin) - 1; j <= Math.ceil(jmax) + 1; j++) {
    for (let i = Math.floor(imin) - 1; i <= Math.ceil(imax) + 1; i++) {
      const x = (i * ca - j * sa) * cell, y = (i * sa + j * ca) * cell;
      if (x < bb[0] - cell || x > bb[2] + cell || y < bb[1] - cell || y > bb[3] + cell) continue;
      const s = fn ? shade(x, y) : shade;
      if (s <= 0.025) continue;
      const r = Math.sqrt(Math.min(s, 0.92)) * k;
      if (r < 0.32 / U) continue;
      g.moveTo(x + r, y); g.arc(x, y, r, 0, TAU);
    }
  }
  g.fillStyle = color; g.fill();
}
const shadeFromNdl = ndl => clamp((0.6 - ndl) / 1.05, 0, 0.86);

function dash(g, x0, y0, x1, y1, w) {
  g.beginPath(); g.moveTo(x0, y0); g.lineTo(x1, y1);
  g.lineWidth = w; g.lineCap = 'round'; g.strokeStyle = CREAM; g.stroke();
}
/* light dashes along the polygon edge that faces the light */
function lightDashes(g, P, w, inset, seed) {
  let cx = 0, cy = 0; for (const p of P) { cx += p[0]; cy += p[1]; } cx /= P.length; cy /= P.length;
  let best = -2, bi = 0;
  for (let i = 0; i < P.length; i++) {
    const a = P[i], b = P[(i + 1) % P.length];
    let nx = b[1] - a[1], ny = a[0] - b[0]; const l = Math.hypot(nx, ny) || 1; nx /= l; ny /= l;
    const mx = (a[0] + b[0]) / 2, my = (a[1] + b[1]) / 2;
    if ((mx - cx) * nx + (my - cy) * ny < 0) { nx = -nx; ny = -ny; }
    const sc = nx * LS[0] + ny * LS[1];
    const len = Math.hypot(b[0] - a[0], b[1] - a[1]);
    if (sc * Math.min(1, len / (inset * 6)) > best) { best = sc * Math.min(1, len / (inset * 6)); bi = i; }
  }
  if (best < 0.15) return;
  const a = P[bi], b = P[(bi + 1) % P.length];
  const ex = b[0] - a[0], ey = b[1] - a[1], len = Math.hypot(ex, ey);
  if (len < inset * 3.2) return;
  let nx = -ey / len, ny = ex / len;
  if ((cx - a[0]) * nx + (cy - a[1]) * ny < 0) { nx = -nx; ny = -ny; }
  const r = hash2(seed, 7);
  const s0 = 0.14 + r * 0.14, s1 = s0 + 0.16 + hash2(seed, 9) * 0.14;
  const s2 = s1 + 0.07, s3 = Math.min(0.86, s2 + 0.06 + hash2(seed, 11) * 0.06);
  const ox = nx * inset, oy = ny * inset;
  dash(g, a[0] + ex * s0 + ox, a[1] + ey * s0 + oy, a[0] + ex * s1 + ox, a[1] + ey * s1 + oy, w);
  if (s3 - s2 > 0.03) dash(g, a[0] + ex * s2 + ox, a[1] + ey * s2 + oy, a[0] + ex * s3 + ox, a[1] + ey * s3 + oy, w);
}

function sparkle(g, x, y, r, rot = 0) {
  g.save(); g.translate(x, y); g.rotate(rot);
  g.beginPath();
  const t = r * 0.16;
  g.moveTo(0, -r); g.quadraticCurveTo(t, -t, r, 0); g.quadraticCurveTo(t, t, 0, r);
  g.quadraticCurveTo(-t, t, -r, 0); g.quadraticCurveTo(-t, -t, 0, -r);
  g.fillStyle = CREAM; g.fill(); g.restore();
}

/* camera shake that loops in 8 s: integer cycles only */
function handheld(s, amp) {
  const w = TAU / LOOP;
  return {
    x: amp * (4.2 * Math.sin(w * 2 * s + 1.3) + 2.1 * Math.sin(w * 5 * s + 0.4) + 0.9 * Math.sin(w * 13 * s + 2.2)),
    y: amp * (3.6 * Math.sin(w * 3 * s + 2.0) + 1.8 * Math.sin(w * 7 * s + 1.1) + 0.8 * Math.sin(w * 17 * s + 0.3)),
    r: amp * (0.0042 * Math.sin(w * 2 * s + 0.7) + 0.0018 * Math.sin(w * 9 * s + 1.9)),
  };
}

/* ------------------------------------------------------------- 3D meshes */
function boxGeom(w, h, d, c) {
  if (!c) {
    return {
      V: [[-w, -h, -d], [w, -h, -d], [w, h, -d], [-w, h, -d], [-w, -h, d], [w, -h, d], [w, h, d], [-w, h, d]],
      F: [
        { i: [4, 5, 6, 7], n: [0, 0, 1], m: 'front' }, { i: [5, 1, 2, 6], n: [1, 0, 0], m: 'right' },
        { i: [7, 6, 2, 3], n: [0, 1, 0], m: 'top' }, { i: [1, 0, 3, 2], n: [0, 0, -1], m: 'back' },
        { i: [0, 4, 7, 3], n: [-1, 0, 0], m: 'left' }, { i: [0, 1, 5, 4], n: [0, -1, 0], m: 'bottom' },
      ],
    };
  }
  // the head: a box whose front-top-right corner is folded away, showing the paper's cream back
  return {
    V: [[-w, -h, -d], [w, -h, -d], [w, h, -d], [-w, h, -d], [-w, -h, d], [w, -h, d], [-w, h, d],
        [w - c, h, d], [w, h - c, d], [w, h, d - c]],
    F: [
      { i: [4, 5, 8, 7, 6], n: [0, 0, 1], m: 'front' },
      { i: [5, 1, 2, 9, 8], n: [1, 0, 0], m: 'right' },
      { i: [6, 7, 9, 2, 3], n: [0, 1, 0], m: 'top' },
      { i: [7, 8, 9], n: norm3([1, 1, 1]), m: 'fold' },
      { i: [1, 0, 3, 2], n: [0, 0, -1], m: 'back' },
      { i: [0, 4, 6, 3], n: [-1, 0, 0], m: 'left' },
      { i: [0, 1, 5, 4], n: [0, -1, 0], m: 'bottom' },
    ],
  };
}
const HEAD = boxGeom(1, 0.86, 0.92, 0.5);
const NECK = boxGeom(0.2, 0.14, 0.2);
const TORSO = boxGeom(0.64, 0.46, 0.56);
const FOOT = boxGeom(0.2, 0.12, 0.26);

/* object: {x, y, k, R, sx, sy, oy}  -> screen units; object y is up */
function proj(o, v) {
  const p = mulMV(o.R, [v[0] * (o.sx || 1), (v[1] + (o.oy || 0)) * (o.sy || 1), v[2] * (o.sx || 1)]);
  return [o.x + o.k * p[0], o.y - o.k * p[1], p[2]];
}

/* draws a convex mesh with flat fills, halftone shade, light dashes, PERI lines */
function drawMesh(g, geom, o, mat, lw, opts = {}) {
  const P = geom.V.map(v => proj(o, v));
  const vis = [];
  for (const f of geom.F) {
    const n = mulMV(o.R, f.n);
    if (n[2] > 0.02) vis.push({ f, n, P: f.i.map(i => P[i]) });
  }
  for (const F of vis) {
    const m = mat[F.f.m] || mat.default;
    poly(g, F.P); g.fillStyle = m.fill; g.fill();
    const s = shadeFromNdl(dot3(F.n, L3)) * (m.shadeK ?? 1) + (m.shadeAdd || 0);
    const bb = bboxOf(F.P);
    const span = Math.max(1, Math.hypot(bb[2] - bb[0], bb[3] - bb[1]));
    const gx = (bb[0] + bb[2]) / 2, gy = (bb[1] + bb[3]) / 2;
    const grad = m.grad ?? 0.22;
    const sf = (x, y) => s + grad * (((x - gx) * -LS[0] + (y - gy) * -LS[1]) / span * 2 + 0.15);
    if (s + grad > 0.04) {
      g.save(); poly(g, F.P); g.clip();
      halftone(g, bb, sf, m.dot, m.cell || 7.5, m.ang ?? Math.PI / 4);
      g.restore();
    }
  }
  for (const F of vis) {
    const m = mat[F.f.m] || mat.default;
    if (m.light !== false && dot3(F.n, L3) > 0.32) lightDashes(g, F.P, lw * 1.25, lw * 2.6, (opts.seed || 0) * 31 + F.f.i[0]);
  }
  g.lineJoin = 'round'; g.lineCap = 'round'; g.strokeStyle = PERI;
  g.lineWidth = lw * 0.55;
  for (const F of vis) { poly(g, F.P); g.stroke(); }
  const hp = hull2(vis.flatMap(F => F.P.map(p => [p[0], p[1]])));
  g.lineWidth = lw; poly(g, hp); g.stroke();
  return { P, vis, hull: hp };
}

/* affine transform that maps a face-local plane (u right, v up) to screen units */
function faceXf(o, origin, du, dv) {
  const a = proj(o, origin), b = proj(o, [origin[0] + du[0], origin[1] + du[1], origin[2] + du[2]]),
        c = proj(o, [origin[0] + dv[0], origin[1] + dv[1], origin[2] + dv[2]]);
  return [b[0] - a[0], b[1] - a[1], c[0] - a[0], c[1] - a[1], a[0], a[1]];
}
function setXf(g, m, base) { // base: roll matrix already on the scene context
  g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
  g.transform(m[0], m[1], m[2], m[3], m[4], m[5]);
}

/* ------------------------------------------------------------ the riders */
/* feet at (x, y); `up` is the screen direction of the body; h is total height */
function eggPath(g, a, b, y0) {
  // egg centred on x=0, bottom at y0, height 2b, width 2a; top a touch narrower
  const T = [0, y0 - 2 * b], Rr = [a, y0 - b * 0.92], B = [0, y0], Lf = [-a, y0 - b * 0.92];
  g.beginPath();
  g.moveTo(T[0], T[1]);
  g.bezierCurveTo(a * 0.6, T[1], a, y0 - b * 1.55, Rr[0], Rr[1]);
  g.bezierCurveTo(a, y0 - b * 0.32, a * 0.6, y0, B[0], B[1]);
  g.bezierCurveTo(-a * 0.6, y0, -a, y0 - b * 0.32, Lf[0], Lf[1]);
  g.bezierCurveTo(-a, y0 - b * 1.55, -a * 0.6, T[1], T[0], T[1]);
  g.closePath();
}
function limb(g, pts, w, lw, fill) {
  g.lineCap = 'round'; g.lineJoin = 'round';
  g.beginPath(); g.moveTo(pts[0][0], pts[0][1]);
  if (pts.length === 3) g.quadraticCurveTo(pts[1][0], pts[1][1], pts[2][0], pts[2][1]);
  else for (let i = 1; i < pts.length; i++) g.lineTo(pts[i][0], pts[i][1]);
  g.strokeStyle = PERI; g.lineWidth = w + lw * 2; g.stroke();
  g.strokeStyle = fill; g.lineWidth = w; g.stroke();
}
function drawRider(g, base, x, y, upAng, h, st) {
  if (h < 3.5) { // a speck at distance
    g.beginPath(); g.arc(x + Math.cos(upAng) * h * 0.5, y + Math.sin(upAng) * h * 0.5, Math.max(0.9, h * 0.38), 0, TAU);
    g.fillStyle = GREEN; g.fill(); return;
  }
  const lw = Math.max(1.4, h * 0.045);
  const stretch = st.stretch || 1, sx = 1 / Math.sqrt(stretch);
  const leg = h * 0.22, b = h * 0.385, a = h * 0.345;
  const rot = upAng + Math.PI / 2;
  g.save();
  g.translate(x, y); g.rotate(rot);
  g.scale(sx, stretch);
  const by = -leg; // body bottom
  // far arm and legs behind the body
  const armY = by - b * 1.0;
  const legPh = st.legPh || 0, legAmp = st.legAmp || 0;
  for (const side of [-1, 1]) {
    const sw = Math.sin(legPh + (side > 0 ? 0 : Math.PI)) * legAmp;
    const fx = side * a * 0.5 + sw * h * 0.2, fy = Math.abs(sw) * -h * 0.06;
    limb(g, [[side * a * 0.34, by - b * 0.2], [side * a * 0.42 + sw * h * 0.1, by + leg * 0.5], [fx, fy - h * 0.03]], h * 0.1, lw, GREEN);
    g.beginPath(); g.ellipse(fx + side * h * 0.035, fy - h * 0.02, h * 0.075, h * 0.045, 0, 0, TAU);
    g.fillStyle = GREEN; g.fill(); g.strokeStyle = PERI; g.lineWidth = lw * 0.9; g.stroke();
  }
  const arm = (side, ang, len) => {
    const sx0 = side * a * 0.86, sy0 = armY;
    const ex = sx0 + Math.cos(ang) * len, ey = sy0 + Math.sin(ang) * len;
    const mx = (sx0 + ex) / 2 + side * len * 0.12, my = (sy0 + ey) / 2 - len * 0.1;
    limb(g, [[sx0, sy0], [mx, my], [ex, ey]], h * 0.095, lw, GREEN);
    return [ex, ey];
  };
  const hands = {};
  if (st.armBehind) { hands.L = arm(-1, st.armL, h * 0.36); }
  // body
  eggPath(g, a, b, by);
  g.fillStyle = GREEN; g.fill();
  // shade: dots on the far side from the light (computed in screen space)
  g.save();
  eggPath(g, a, b, by); g.clip();
  const m = g.getTransform();
  g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
  const cxs = x + Math.cos(upAng) * (leg + b) * stretch, cys = y + Math.sin(upAng) * (leg + b) * stretch;
  const rS = b * 1.08;
  halftone(g, [cxs - rS * 1.4, cys - rS * 1.4, cxs + rS * 1.4, cys + rS * 1.4], (px, py) => {
    const dx = (px - cxs) / rS, dy = (py - cys) / rS;
    const lit = dx * LS[0] + dy * LS[1];
    const rr = Math.hypot(dx, dy);
    return clamp((-lit - 0.12) * 0.62 + Math.max(0, rr - 0.84) * 0.8, 0, 0.5);
  }, COBALT, Math.max(4.2, Math.min(6, h * 0.07)), Math.PI / 12);
  g.setTransform(m);
  g.restore();
  // a cream dash of light on the upper left rim (in screen space)
  {
    const m2 = g.getTransform();
    g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
    const la = Math.atan2(LS[1], LS[0]);
    g.beginPath(); g.arc(cxs, cys, rS * 0.74, la - 0.55, la - 0.08);
    g.strokeStyle = CREAM; g.lineWidth = lw * 1.25; g.lineCap = 'round'; g.stroke();
    if (h > 14) { g.beginPath(); g.arc(cxs, cys, rS * 0.74, la + 0.12, la + 0.26); g.stroke(); }
    g.setTransform(m2);
  }
  eggPath(g, a, b, by);
  g.strokeStyle = PERI; g.lineWidth = lw; g.stroke();
  // the eye
  const ey = by - b * 1.22, er = a * 0.56;
  g.beginPath(); g.arc(0, ey, er, 0, TAU); g.fillStyle = CREAM; g.fill();
  g.save(); g.beginPath(); g.arc(0, ey, er, 0, TAU); g.clip();
  const lx = (st.lookX || 0) * er * 0.42, ly = (st.lookY || 0) * er * 0.42;
  const pr = er * (st.pupil || 0.5);
  g.beginPath(); g.arc(lx, ly + ey, pr, 0, TAU); g.fillStyle = INK; g.fill();
  g.beginPath(); g.arc(lx - pr * 0.38, ly + ey - pr * 0.4, pr * 0.3, 0, TAU); g.fillStyle = CREAM; g.fill();
  const open = st.open ?? 1;
  if (open < 0.999) {
    g.fillStyle = GREEN; g.fillRect(-er * 1.2, ey - er * 1.2, er * 2.4, er * 2.4 * (1 - open));
    g.beginPath(); g.moveTo(-er, ey - er * 1.2 + er * 2.4 * (1 - open)); g.lineTo(er, ey - er * 1.2 + er * 2.4 * (1 - open));
    g.strokeStyle = PERI; g.lineWidth = lw * 0.8; g.stroke();
  }
  g.restore();
  g.beginPath(); g.arc(0, ey, er, 0, TAU); g.strokeStyle = PERI; g.lineWidth = lw * 0.85; g.stroke();
  // little sprout on top
  limb(g, [[0, by - 2 * b + lw], [a * 0.12, by - 2 * b - h * 0.08], [a * 0.3, by - 2 * b - h * 0.1]], h * 0.04, lw * 0.7, GREEN);
  // arms in front
  if (!st.armBehind) hands.L = arm(-1, st.armL, h * 0.36);
  hands.R = arm(1, st.armR, h * 0.36);
  g.restore();
  // hand positions in screen space (for ropes)
  const toScreen = (p) => {
    const px = p[0] * sx, py = p[1] * stretch;
    const c = Math.cos(rot), s = Math.sin(rot);
    return [x + px * c - py * s, y + px * s + py * c];
  };
  return { L: toScreen(hands.L), R: toScreen(hands.R) };
}

/* --------------------------------------------------------- the robot */
const ROBOT_MAT = {
  front: { fill: COBALT, dot: INK, cell: 7.5 },
  right: { fill: COBALT, dot: INK, cell: 7.5 },
  top: { fill: COBALT, dot: INK, cell: 7.5 },
  fold: { fill: CREAM, dot: PERI, cell: 7, shadeK: 0.9, light: false, ang: Math.PI * 5 / 12, grad: 0.12 },
  default: { fill: COBALT, dot: INK, cell: 7.5 },
};

function drawEye(g, base, o, ex, ey, st, k) {
  // eye decal on the front plane (u right, v up), radius in head units
  const z = 0.92 + 0.004;
  const xf = faceXf(o, [ex, ey, z], [1, 0, 0], [0, 1, 0]);
  const r = 0.29 * st.eyeScale;
  const lwL = (st.lw / k);
  setXf(g, xf, base);
  g.beginPath(); g.ellipse(0, 0, r, r, 0, 0, TAU); g.fillStyle = CREAM; g.fill();
  g.save();
  g.beginPath(); g.ellipse(0, 0, r, r, 0, 0, TAU); g.clip();
  // pupil (local v is up)
  const px = st.lookX * r * 0.4, py = st.lookY * r * 0.4;
  const pr = r * 0.5 * st.pupil;
  g.beginPath(); g.arc(px, py, pr, 0, TAU); g.fillStyle = INK; g.fill();
  if (st.sparkle < 0.5) {
    g.beginPath(); g.arc(px - pr * 0.36, py + pr * 0.4, pr * 0.28, 0, TAU); g.fillStyle = CREAM; g.fill();
    g.beginPath(); g.arc(px + pr * 0.34, py - pr * 0.36, pr * 0.11, 0, TAU); g.fillStyle = CREAM; g.fill();
  }
  // a shade crescent of PERI dots inside the eye, lower right, in screen space
  const m = g.getTransform();
  g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
  const c = proj(o, [ex, ey, z]);
  const rS = r * k;
  halftone(g, [c[0] - rS, c[1] - rS, c[0] + rS, c[1] + rS], (x, y) => {
    const dx = (x - c[0]) / rS, dy = (y - c[1]) / rS;
    const lit = dx * LS[0] + dy * LS[1];
    return clamp((-lit - 0.25) * 0.6 + Math.max(0, Math.hypot(dx, dy) - 0.82) * 1.2, 0, 0.55);
  }, PERI, 6.5, Math.PI * 5 / 12);
  g.setTransform(m);
  // the lid: cobalt, coming down from the top
  const open = st.open;
  if (open < 0.999) {
    const yl = r - 2 * r * (1 - open);
    g.beginPath(); g.rect(-r * 1.2, yl, r * 2.4, r * 1.3);
    g.fillStyle = COBALT; g.fill();
    g.beginPath(); g.moveTo(-r * 1.1, yl); g.quadraticCurveTo(0, yl - r * 0.12, r * 1.1, yl);
    g.strokeStyle = PERI; g.lineWidth = lwL * 0.9; g.stroke();
  }
  g.restore();
  g.beginPath(); g.ellipse(0, 0, r, r, 0, 0, TAU);
  g.strokeStyle = PERI; g.lineWidth = lwL * 0.8; g.stroke();
  g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
  // wonder: four-point star glints inside the pupil (screen space, crisp)
  if (st.sparkle > 0.01) {
    const p = proj(o, [ex + px - pr * 0.3, ey + py + pr * 0.32, z]);
    sparkle(g, p[0], p[1], pr * k * 0.62 * st.sparkle, 0.12);
    const p2 = proj(o, [ex + px + pr * 0.42, ey + py - pr * 0.38, z]);
    sparkle(g, p2[0], p2[1], pr * k * 0.26 * st.sparkle, -0.2);
  }
}

function drawEar(g, base, o, st, k) {
  // vermilion disc on the right face, extruded outward along +x
  const w = 1, lwL = st.lw / k, r = 0.34;
  const off = st.earOff || [0, 0];
  const layers = 6, depth = 0.17;
  const xfAt = d => faceXf(o, [w + d, -0.06 + off[1], off[0]], [0, 0, -1], [0, 1, 0]);
  // body of the disc: stacked ellipses
  for (let i = 0; i <= layers; i++) {
    setXf(g, xfAt(depth * i / layers), base);
    g.beginPath(); g.arc(0, 0, r, 0, TAU); g.fillStyle = VERM; g.fill();
  }
  // shade the rim band with ink dots
  g.save();
  g.beginPath();
  for (let i = 0; i <= layers; i++) {
    const m = xfAt(depth * i / layers);
    // build each ellipse in screen space via transform math
    const steps = 36;
    for (let j = 0; j <= steps; j++) {
      const a = j / steps * TAU, u = Math.cos(a) * r, v = Math.sin(a) * r;
      const X = m[0] * u + m[2] * v + m[4], Y = m[1] * u + m[3] * v + m[5];
      if (j === 0) g.moveTo(X, Y); else g.lineTo(X, Y);
    }
    g.closePath();
  }
  g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
  g.clip('nonzero');
  const c = proj(o, [w, -0.06, 0]);
  halftone(g, [c[0] - r * k * 1.6, c[1] - r * k * 1.6, c[0] + r * k * 1.6, c[1] + r * k * 1.6], 0.62, INK, 7.2, Math.PI / 4);
  g.restore();
  // the face of the disc
  const fm = xfAt(depth);
  setXf(g, fm, base);
  g.beginPath(); g.arc(0, 0, r, 0, TAU); g.fillStyle = VERM; g.fill();
  g.save(); g.beginPath(); g.arc(0, 0, r, 0, TAU); g.clip();
  const mm = g.getTransform();
  g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
  const cf = [fm[4], fm[5]], rS = Math.hypot(fm[0], fm[1]) * r;
  halftone(g, [cf[0] - rS * 1.5, cf[1] - rS * 1.5, cf[0] + rS * 1.5, cf[1] + rS * 1.5], (x, y) => {
    const dx = (x - cf[0]) / rS, dy = (y - cf[1]) / rS;
    return clamp(0.12 + (dx * -LS[0] + dy * -LS[1]) * 0.35, 0, 0.5);
  }, INK, 7.2, Math.PI / 4);
  g.setTransform(mm);
  g.restore();
  g.beginPath(); g.arc(0, 0, r, 0, TAU); g.strokeStyle = PERI; g.lineWidth = lwL * 0.9; g.stroke();
  g.beginPath(); g.arc(0, 0, r * 0.52, 0, TAU); g.lineWidth = lwL * 0.5; g.stroke();
  // light on the disc
  g.beginPath(); g.arc(0, 0, r * 0.76, Math.PI * 0.62, Math.PI * 0.9);
  g.strokeStyle = CREAM; g.lineWidth = lwL * 1.2; g.lineCap = 'round'; g.stroke();
  // back edge outline
  setXf(g, xfAt(0), base);
  g.beginPath(); g.arc(0, 0, r, 0, TAU); g.strokeStyle = PERI; g.lineWidth = lwL * 0.9;
  g.save(); setXf(g, fm, base); g.beginPath(); g.rect(-9, -9, 18, 18); g.arc(0, 0, r, 0, TAU, true); g.restore();
  g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
}

/* the paper robot. pose: {x,y,k,yaw,pitch,roll,sy, eye state..., arms (full only)} */
function drawRobot(g, base, pose, full) {
  const k = pose.k;
  const lw = Math.max(1.6, k * 0.022);
  const Rb = mulM(rotZ(pose.roll), mulM(rotX(pose.pitch), rotY(pose.yaw)));
  const Rh = mulM(Rb, mulM(rotX(pose.headPitch || 0), rotY(pose.headYaw || 0)));
  const sy = pose.sy || 1, sx = 1 / Math.sqrt(sy);
  const headO = { x: pose.x, y: pose.y, k, R: Rh, sx, sy };
  // body hangs below the head: neck and torso in the body frame
  const neckY = -0.86 - 0.12, torsoY = -0.86 - 0.24 - 0.46;
  const bodyO = (oy) => ({ x: pose.x, y: pose.y, k, R: Rb, oy, sx: 1, sy: 1 });
  const bodyMat = {
    default: { fill: COBALT, dot: INK, cell: 7.5 },
  };
  const P = (o, v) => proj(o, v);
  const limbW = k * 0.2;
  const armPts = (side) => {
    const sh = P(bodyO(torsoY), [side * 0.7, 0.28, 0]);
    const a1 = pose.arm[side > 0 ? 1 : 0];
    const el = [sh[0] + Math.cos(a1[0]) * k * 0.55, sh[1] + Math.sin(a1[0]) * k * 0.55];
    const ha = [el[0] + Math.cos(a1[1]) * k * 0.5, el[1] + Math.sin(a1[1]) * k * 0.5];
    return [sh, el, ha];
  };
  const legPts = (side) => {
    const hp = P(bodyO(torsoY), [side * 0.34, -0.44, 0]);
    const l1 = pose.leg[side > 0 ? 1 : 0];
    const kn = [hp[0] + Math.cos(l1[0]) * k * 0.42, hp[1] + Math.sin(l1[0]) * k * 0.42];
    const ft = [kn[0] + Math.cos(l1[1]) * k * 0.4, kn[1] + Math.sin(l1[1]) * k * 0.4];
    return [hp, kn, ft];
  };
  const drawLimb = (pts) => {
    limb(g, pts, limbW, lw, COBALT);
    // shade dash on the limb (ink) and light dash (cream)
    const [a, b, c] = pts;
    g.beginPath(); g.arc(c[0], c[1], limbW * 0.62, 0, TAU); g.fillStyle = COBALT; g.fill();
    g.strokeStyle = PERI; g.lineWidth = lw; g.stroke();
    dash(g, lerp(a[0], b[0], 0.25) - limbW * 0.22, lerp(a[1], b[1], 0.25) - limbW * 0.22, lerp(a[0], b[0], 0.6) - limbW * 0.22, lerp(a[1], b[1], 0.6) - limbW * 0.22, lw * 1.1);
  };
  if (full) {
    // far limbs (robot's left = -x, away from us when yaw < 0)
    drawLimb(legPts(-1));
    drawLimb(armPts(-1));
    drawMesh(g, TORSO, bodyO(torsoY), bodyMat, lw, { seed: 2 });
    drawLimb(legPts(1));
  } else {
    drawMesh(g, TORSO, bodyO(torsoY), bodyMat, lw, { seed: 2 });
  }
  drawMesh(g, NECK, bodyO(neckY), bodyMat, lw * 0.8, { seed: 3 });
  const head = drawMesh(g, HEAD, headO, ROBOT_MAT, lw, { seed: 1 });
  const frontVis = mulMV(Rh, [0, 0, 1])[2] > 0.05;
  const st = Object.assign({ lw }, pose.eyes);
  if (frontVis) {
    drawEye(g, base, headO, -0.45, -0.04, st, k);
    drawEye(g, base, headO, 0.38, -0.04, st, k);
  }
  if (mulMV(Rh, [1, 0, 0])[2] > 0.02) drawEar(g, base, Object.assign({}, headO), Object.assign({ earOff: pose.earOff }, st), k);
  if (full) drawLimb(armPts(1));
  return head;
}

const STARS = (() => {
  const rnd = mulberry32(4242);
  const out = [];
  // the false-lock star, placed where the reticle will look
  out.push({ x: 432, y: 0.29, r: 3.4, e: 0.55, par: 0.75, tw: 0, kind: 2, cyc: 2 });
  for (let i = 0; i < 230; i++) {
    const near = rnd() < 0.28;
    out.push({
      x: -260 + rnd() * 1520, y: -0.16 + rnd() * 1.32,
      r: near ? 2.2 + rnd() * 2.0 : 1.0 + rnd() * 1.4,
      e: near ? 0.62 : 0.36, par: near ? 0.85 : 0.5,
      tw: rnd() * TAU, kind: near && rnd() < 0.18 ? 2 : (rnd() < 0.5 ? 1 : 0),
      cyc: 1 + Math.floor(rnd() * 3),
    });
  }
  return out;
})();

function buildFarTex() {
  // nebula of halftone dots and faint stars, cached at 1.45x so zoom stays crisp
  TEX.h = H + 840;
  TEX.fs = U * 1.45;
  const c = document.createElement('canvas');
  c.width = Math.ceil(TEX.w * TEX.fs); c.height = Math.ceil(TEX.h * TEX.fs);
  const g = c.getContext('2d');
  g.setTransform(TEX.fs, 0, 0, TEX.fs, -TEX.x0 * TEX.fs, -TEX.y0 * TEX.fs);
  g.fillStyle = INK; g.fillRect(TEX.x0, TEX.y0, TEX.w, TEX.h);
  const bb = [TEX.x0, TEX.y0, TEX.x0 + TEX.w, TEX.y0 + TEX.h];
  // two inks of nebula: cobalt (broad) and peri (wisps)
  halftone(g, bb, (x, y) => {
    const n = fbm(x * 0.0021 + 3.1, y * 0.0021 + 1.7);
    const band = Math.exp(-Math.pow((y - 0.33 * H - (x - 500) * 0.55) / 520, 2));
    return clamp((n - 0.5) * 1.9 * band, 0, 0.3);
  }, COBALT, 8, Math.PI / 12);
  halftone(g, bb, (x, y) => {
    const n = fbm(x * 0.0034 + 9.2, y * 0.0034 + 4.4);
    const band = Math.exp(-Math.pow((y - 0.3 * H - (x - 500) * 0.6) / 360, 2));
    return clamp((n - 0.56) * 2.2 * band, 0, 0.26);
  }, PERI, 7, Math.PI * 5 / 12);
  // faint far stars
  const rnd = mulberry32(777);
  g.fillStyle = CREAM;
  for (let i = 0; i < 520; i++) {
    const x = TEX.x0 + rnd() * TEX.w, y = TEX.y0 + rnd() * TEX.h, r = 0.55 + rnd() * rnd() * 1.3;
    g.beginPath(); g.arc(x, y, r, 0, TAU); g.fill();
  }
  g.fillStyle = PERI;
  for (let i = 0; i < 380; i++) {
    const x = TEX.x0 + rnd() * TEX.w, y = TEX.y0 + rnd() * TEX.h, r = 0.6 + rnd() * 1.1;
    g.beginPath(); g.arc(x, y, r, 0, TAU); g.fill();
  }
  farTex = c;
}

function buildGrain() {
  grains = [];
  const w = Math.ceil(Wpx / 1.5), h = Math.ceil(Hpx / 1.5);
  const rnd = mulberry32(1234);
  const cr = [251, 237, 210], ik = [27, 23, 71];
  for (let f = 0; f < 4; f++) {
    const c = document.createElement('canvas'); c.width = w; c.height = h;
    const g = c.getContext('2d');
    const id = g.createImageData(w, h), d = id.data;
    for (let i = 0; i < w * h; i++) {
      const r = rnd();
      if (r < 0.055) { d[i * 4] = cr[0]; d[i * 4 + 1] = cr[1]; d[i * 4 + 2] = cr[2]; d[i * 4 + 3] = 14 + rnd() * 26; }
      else if (r < 0.14) { d[i * 4] = ik[0]; d[i * 4 + 1] = ik[1]; d[i * 4 + 2] = ik[2]; d[i * 4 + 3] = 30 + rnd() * 40; }
    }
    g.putImageData(id, 0, 0);
    grains.push(c);
  }
}

/* bg camera: {ax, ay} anchor on screen, {px, py} same point in star space, Z zoom, d offset */
function starScreen(st, cam) {
  const ze = Math.pow(cam.Z, st.e);
  return [cam.ax + (st.x - cam.px) * ze + cam.dx * st.par, cam.ay + (st.y * H - cam.py) * ze + cam.dy * st.par];
}
function drawBG(g, cam, camPrev, s) {
  // far layer: nebula texture
  const zf = Math.pow(cam.Z, 0.12);
  g.save();
  g.translate(cam.ax + cam.dx * 0.25, cam.ay + cam.dy * 0.25);
  g.scale(zf, zf);
  g.translate(-cam.px, -cam.py);
  g.drawImage(farTex, TEX.x0, TEX.y0, TEX.w, TEX.h);
  g.restore();
  // near stars, procedural, with zoom streaks
  g.lineCap = 'round';
  for (let i = 0; i < STARS.length; i++) {
    const st = STARS[i];
    const p = starScreen(st, cam);
    if (p[0] < -60 || p[0] > 1060 || p[1] < -60 || p[1] > H + 60) continue;
    const q = camPrev ? starScreen(st, camPrev) : p;
    const tw = 0.75 + 0.25 * Math.sin(TAU * st.cyc * s / LOOP + st.tw);
    const streak = Math.hypot(p[0] - q[0], p[1] - q[1]);
    if (streak > st.r * 1.5) {
      g.beginPath(); g.moveTo(q[0], q[1]); g.lineTo(p[0], p[1]);
      g.strokeStyle = st.kind === 1 ? PERI : CREAM; g.lineWidth = st.r * 1.5; g.stroke();
    } else if (st.kind === 2) {
      sparkle(g, p[0], p[1], st.r * 3.4 * tw, 0);
      g.beginPath(); g.arc(p[0], p[1], st.r * 0.55, 0, TAU); g.fillStyle = CREAM; g.fill();
    } else {
      g.beginPath(); g.arc(p[0], p[1], st.r * tw, 0, TAU); g.fillStyle = st.kind === 1 ? PERI : CREAM; g.fill();
    }
  }
}

/* ------------------------------------------------------------ dot-matrix */
const GLYPHS = {
  '0': ['.###.', '#...#', '#..##', '#.#.#', '##..#', '#...#', '.###.'],
  '1': ['..#..', '.##..', '..#..', '..#..', '..#..', '..#..', '.###.'],
  '2': ['.###.', '#...#', '....#', '...#.', '..#..', '.#...', '#####'],
  '3': ['#####', '...#.', '..#..', '...#.', '....#', '#...#', '.###.'],
  '4': ['...#.', '..##.', '.#.#.', '#..#.', '#####', '...#.', '...#.'],
  '5': ['#####', '#....', '####.', '....#', '....#', '#...#', '.###.'],
  '6': ['..##.', '.#...', '#....', '####.', '#...#', '#...#', '.###.'],
  '7': ['#####', '....#', '...#.', '..#..', '.#...', '.#...', '.#...'],
  '8': ['.###.', '#...#', '#...#', '.###.', '#...#', '#...#', '.###.'],
  '9': ['.###.', '#...#', '#...#', '.####', '....#', '...#.', '.##..'],
  ':': ['.', '.', '#', '.', '#', '.', '.'],
  '.': ['.', '.', '.', '.', '.', '.', '#'],
  ' ': ['...', '...', '...', '...', '...', '...', '...'],
  'A': ['.###.', '#...#', '#...#', '#####', '#...#', '#...#', '#...#'],
  'C': ['.###.', '#...#', '#....', '#....', '#....', '#...#', '.###.'],
  'E': ['#####', '#....', '#....', '####.', '#....', '#....', '#####'],
  'F': ['#####', '#....', '#....', '####.', '#....', '#....', '#....'],
  'K': ['#...#', '#..#.', '#.#..', '##...', '#.#..', '#..#.', '#...#'],
  'L': ['#....', '#....', '#....', '#....', '#....', '#....', '#####'],
  'O': ['.###.', '#...#', '#...#', '#...#', '#...#', '#...#', '.###.'],
  'P': ['####.', '#...#', '#...#', '####.', '#....', '#....', '#....'],
  'R': ['####.', '#...#', '#...#', '####.', '#.#..', '#..#.', '#...#'],
  'S': ['.####', '#....', '#....', '.###.', '....#', '....#', '####.'],
  'T': ['#####', '..#..', '..#..', '..#..', '..#..', '..#..', '..#..'],
  'W': ['#...#', '#...#', '#...#', '#.#.#', '#.#.#', '##.##', '#...#'],
  'x': ['.....', '.....', '#...#', '.#.#.', '..#..', '.#.#.', '#...#'],
  '!': ['#', '#', '#', '#', '#', '.', '#'],
};
function textWidth(str, pitch) {
  let w = 0; for (const ch of str) { const gl = GLYPHS[ch] || GLYPHS[' ']; w += (gl[0].length + 1) * pitch; } return w - pitch;
}
function dotText(g, str, x, y, pitch, color, align = 'left') {
  if (align === 'right') x -= textWidth(str, pitch);
  if (align === 'center') x -= textWidth(str, pitch) / 2;
  g.beginPath();
  const r = pitch * 0.4;
  for (const ch of str) {
    const gl = GLYPHS[ch] || GLYPHS[' '];
    for (let row = 0; row < 7; row++) for (let col = 0; col < gl[row].length; col++) {
      if (gl[row][col] === '#') { const cx = x + col * pitch + pitch / 2, cy = y + row * pitch + pitch / 2; g.moveTo(cx + r, cy); g.arc(cx, cy, r, 0, TAU); }
    }
    x += (gl[0].length + 1) * pitch;
  }
  g.fillStyle = color; g.fill();
}

/* --------------------------------------------------------------- overlay */
function bracketBox(g, cx, cy, w, h, lw, arm) {
  const x0 = cx - w / 2, x1 = cx + w / 2, y0 = cy - h / 2, y1 = cy + h / 2;
  const a = Math.min(arm, w * 0.4, h * 0.4);
  g.beginPath();
  g.moveTo(x0, y0 + a); g.lineTo(x0, y0); g.lineTo(x0 + a, y0);
  g.moveTo(x1 - a, y0); g.lineTo(x1, y0); g.lineTo(x1, y0 + a);
  g.moveTo(x1, y1 - a); g.lineTo(x1, y1); g.lineTo(x1 - a, y1);
  g.moveTo(x0 + a, y1); g.lineTo(x0, y1); g.lineTo(x0, y1 - a);
  g.lineWidth = lw; g.lineCap = 'round'; g.lineJoin = 'round'; g.strokeStyle = CREAM; g.stroke();
}
function cross(g, x, y, r, lw) {
  g.beginPath(); g.moveTo(x - r, y); g.lineTo(x - r * 0.35, y); g.moveTo(x + r * 0.35, y); g.lineTo(x + r, y);
  g.moveTo(x, y - r); g.lineTo(x, y - r * 0.35); g.moveTo(x, y + r * 0.35); g.lineTo(x, y + r);
  g.lineWidth = lw; g.strokeStyle = CREAM; g.lineCap = 'round'; g.stroke();
}

/* ============================================================================
   THE OPENING — "the overlay is the plot", now introducing the newest film.

   A full-page camcorder shot drawn in code, in the evidence loop's own rules
   (six colours, never black, halftone shade, cream-dash light, film grain, a
   crisp viewfinder overlay). The camera finds the paper robot, whips up, hunts
   across the stars, false-locks a star, then locks onto a folded-paper screen
   drifting in space. It zooms in; the screen tunes in from static to the newest
   film's own code-drawn title card; the riders cling to its frame. Then it
   holds: a slow handheld drift, REC blinking, the tape playing.

   Timeline (seconds)
     0.00-2.35  close-up: the robot gasps, wonders, blinks, looks toward the screen; whip pan
     2.35-4.30  wide, over the robot's shoulder: the reticle hunts, false-locks a star, locks the screen
     4.30-5.50  zoom: the screen grows from a speck to the hero; stars streak; the AF hunts
     5.50-      hold: the screen plays the title card; the page's film details fade in

   The page's words are real HTML beside the shot; only the camera's own UI
   (REC, timecode, tape counter, battery, zoom bar, reticle, AF, date) is drawn.
   ========================================================================== */

/* ------------------------------------------------------------ more glyphs */
Object.assign(GLYPHS, {
  'B': ['####.', '#...#', '#...#', '####.', '#...#', '#...#', '####.'],
  'D': ['####.', '#...#', '#...#', '#...#', '#...#', '#...#', '####.'],
  'G': ['.###.', '#...#', '#....', '#.###', '#...#', '#...#', '.###.'],
  'H': ['#...#', '#...#', '#...#', '#####', '#...#', '#...#', '#...#'],
  'I': ['###', '.#.', '.#.', '.#.', '.#.', '.#.', '###'],
  'M': ['#...#', '##.##', '#.#.#', '#.#.#', '#...#', '#...#', '#...#'],
  'N': ['#...#', '##..#', '#.#.#', '#..##', '#...#', '#...#', '#...#'],
  'U': ['#...#', '#...#', '#...#', '#...#', '#...#', '#...#', '.###.'],
  'V': ['#...#', '#...#', '#...#', '#...#', '#...#', '.#.#.', '..#..'],
  'Y': ['#...#', '#...#', '.#.#.', '..#..', '..#..', '..#..', '..#..'],
  '/': ['....#', '...#.', '...#.', '..#..', '.#...', '.#...', '#....'],
  '-': ['.....', '.....', '.....', '#####', '.....', '.....', '.....'],
  '>': ['#....', '##...', '###..', '####.', '###..', '##...', '#....'],
});

/* --------------------------------------------------------------- the films */
// Newest first. Text lives in the page's HTML; these drive the shot.
const TAPES = {
  '02': { n: '02', art: () => (typeof FILM2 !== 'undefined' ? FILM2 : null), date: 'SEP 08 2026', runtime: '06:27', reveal: 4.7, hold: [4.7, 6.8] },
  '01': { n: '01', art: () => (typeof FILM1 !== 'undefined' ? FILM1 : null), date: 'SEP 06 2026', runtime: '07:29', reveal: 2.9, hold: [3.0, 6.8] },
};
const ORDER = ['02', '01'];
const T_SET = 5.5;

/* ---------------------------------------------------------------- layout */
let LY = null;
function computeLayout(cssW, cssH) {
  const wide = cssW / cssH >= 1.12;
  const uc = cssW / 1000;                 // css px per unit
  const q = 1 / uc;                       // units per css px
  const headU = (wide ? 96 : 118) * q;
  if (wide) {
    const sw = Math.min(520, (H * 0.56) / 0.5625, 430 + (H - 560) * 0.2);
    const set = { x: 708, y: Math.max(headU + sw * 0.34 + 40 * q, H * 0.52), w: sw };
    return {
      wide, uc, q, headU, set,
      far: { x: 742, y: Math.max(headU + 130 * q, H * 0.36), w: 30 },
      close: { x: 700, y: H * 0.7, k: H * 0.28 },
      over: { x: 872, y: H * 0.8, k: H * 0.1, mirror: true },
      lookSign: -1,
      hunt: [[690, H * 0.5, 250 * 1, 250], [588, H * 0.4, 210, 210], [846, H * 0.36, 210, 210]],
      star: [616, 0.22],
      full: [700, H * 0.55, 560, H - headU - 120 * q],
      riders: [
        { id: 'A', at: [-0.42, 0.66], edge: 'top' },
        { id: 'B', at: [0.5, 0.66], edge: 'top' },
        { id: 'D', at: [-0.7, -0.66], edge: 'hang' },
      ],
      ov: { l: 470, r: 40 * q, b: 30 * q },
      rollC: [700, H * 0.5],
    };
  }
  // tall: the shot sits above the words, which fill the lower half
  const sw = 780;
  const set = { x: 500, y: headU + 70 * q + sw * 0.5625 / 2 + 0.08 * sw / 1.84, w: sw };
  return {
    wide, uc, q, headU, set,
    far: { x: 650, y: headU + 60 * q, w: 50 },
    close: { x: 520, y: set.y - 70, k: 212 },
    over: { x: 215, y: set.y + 150, k: 80, mirror: false },
    lookSign: 1,
    hunt: [[500, set.y, 380, 380], [330, set.y - 120, 320, 320], [700, set.y - 200, 320, 320]],
    star: [380, (headU + 160 * q) / H],
    full: [500, set.y + 60, 900, 900],
    riders: [
      { id: 'A', at: [-0.06, 0.66], edge: 'top' },
      { id: 'B', at: [0.6, 0.66], edge: 'top' },
    ],
    ov: { l: 36 * q, r: 36 * q, b: 0 },
    rollC: [500, set.y],
  };
}

/* ------------------------------------------------------------- the screen */
// a folded-paper screen: the bezel is a shallow box, the picture sits on its front
const SCREEN = boxGeom(1.0, 0.66, 0.07);
const PIC = { u0: -0.92, v0: 0.58, w: 1.84, h: 1.035 };   // the picture, in object units
const PIC_CY = PIC.v0 - PIC.h / 2;                          // its centre, above the box centre
const SCREEN_MAT = {
  front: { fill: VERM, dot: INK, cell: 6.5, shadeK: 0.55, grad: 0.16 },
  default: { fill: VERM, dot: INK, cell: 6.5, shadeAdd: 0.08 },
};

/* the card each tape plays: built once per size with the film's own renderer */
const cards = {};
function cardFor(n) {
  const T = TAPES[n], art = T.art();
  if (!art) return null;
  const cw = Math.max(160, Math.round(Math.min(1280, LY.set.w * U))), ch = Math.round(cw * 9 / 16);
  let c = cards[n];
  if (!c || c.cw !== cw) {
    const canvas = document.createElement('canvas'); canvas.width = cw; canvas.height = ch;
    c = cards[n] = { n, cw, ch, canvas, ctx: canvas.getContext('2d'), gen: null, state: null, lastDraw: -1, lastT: null };
  }
  return c;
}
function stepCard(c, budgetMs) {
  if (!c || c.state) return true;
  const art = TAPES[c.n].art();
  if (!c.gen) c.gen = art.build('title', c.cw, c.ch);
  const until = performance.now() + budgetMs;
  while (performance.now() < until) {
    const r = c.gen.next();
    if (r.done) { c.state = r.value; c.gen = null; return true; }
  }
  return false;
}
function buildCardNow(c) { if (!c) return; while (!stepCard(c, 1000)); }
/* card clock: play the reveal once, then hold by drifting back and forth inside the finished part */
function cardClock(n, since) {
  const T = TAPES[n];
  if (since <= T.reveal) return Math.max(0, since);
  const span = T.hold[1] - T.hold[0], ph = ((since - T.reveal) / span) % 2;
  return T.hold[0] + span * (ph < 1 ? ph : 2 - ph);
}
function paintCard(c, tc, force) {
  if (!c || !c.state) return false;
  if (!force && c.lastT !== null && Math.abs(tc - c.lastT) < 1 / 15) return true;
  TAPES[c.n].art().draw(c.state, c.ctx, tc);
  c.lastT = tc;
  return true;
}

/* ------------------------------------------------------------------ state */
const st8 = { tape: '02', tunedAt: null, switchAt: null, prevTape: null, tStart: 0 };

/* ------------------------------------------------------------------ shots */
function closeCam(s) {
  const hh = handheld(s, 1.0);
  const whip = s > 2.1 ? 1300 * ein(inv(2.1, 2.35, s)) : 0;
  return { ax: LY.close.x, ay: H / 2, px: 520, py: H * 0.5 + 520, Z: 1 + 0.035 * s, dx: hh.x, dy: hh.y + whip, roll: hh.r, whip };
}
function closeRobotPose(s) {
  const cam = closeCam(s), kk = LY.close.k / 338, ls = LY.lookSign;
  const sp = spring(s, 15, 5.2);
  const lookT = eback(inv(1.25, 1.55, s));
  const antic = sstep(1.85, 2.08, s);
  const sy = 1 + 0.12 * sp - 0.05 * antic;
  const blink = bump(0.95, 1.02, 1.14, s);
  const sparkleV = sstep(0.26, 0.4, s) * (1 - sstep(0.92, 1.0, s)) * (0.86 + 0.14 * Math.sin(TAU * 24 * s / LOOP));
  return {
    x: LY.close.x + cam.dx + 18 * kk * lookT * ls,
    y: LY.close.y + cam.dy + kk * (6 * Math.sin(TAU * s / LOOP * 2) + 34 * antic - 20 * sp - 26 * lookT),
    k: LY.close.k * cam.Z,
    yaw: -0.5 + 0.13 * lookT * ls, pitch: 0.27 - 0.13 * lookT + 0.06 * antic, roll: 0.025 * Math.sin(TAU * s / LOOP) - 0.03 * sp + cam.roll,
    headYaw: 0, headPitch: 0, sy,
    eyes: {
      eyeScale: 1 + 0.2 * Math.exp(-4.5 * s) * (1 + 0.15 * Math.cos(16 * s)),
      pupil: 0.6 + 0.4 * sstep(0.0, 0.3, s) + 0.5 * sparkleV - 0.06 * lookT * (1 - antic),
      lookX: ls * lerp(-0.08, 0.72, lookT), lookY: lerp(0.0, 0.78, lookT),
      open: 1 - blink * 0.98 - 0.12 * sstep(1.75, 1.95, s) + 0.12 * antic,
      sparkle: sparkleV,
    },
    earOff: [0.06 * spring(s - 0.02, 21, 5.5) + 0.04 * spring(s - 1.3, 24, 6), 0.05 * spring(s, 17, 5) - 0.03 * spring(s - 1.3, 20, 6)],
  };
}
function drawClose(g, base, s) {
  const cam = closeCam(s), camPrev = closeCam(Math.max(0, s - 0.035));
  drawBG(g, cam, camPrev, s);
  const pose = closeRobotPose(s);
  drawRobot(g, base, pose, false);
  const e = 1 - sstep(0.05, 0.45, s);
  if (e > 0.01) {
    const cx = pose.x, cy = pose.y - pose.k * 0.95, sc = eout(inv(0, 0.18, s));
    for (const [ang, len] of [[-2.25, 1], [-1.62, 1.25], [-1.0, 1]]) {
      const r0 = pose.k * (0.98 + 0.22 * sc), r1 = r0 + pose.k * 0.2 * len * e;
      dash(g, cx + Math.cos(ang) * r0 * 1.05, cy + Math.sin(ang) * r0 * 0.62, cx + Math.cos(ang) * r1 * 1.05, cy + Math.sin(ang) * r1 * 0.62, pose.k * 0.026);
    }
  }
}

/* the wide, the zoom and the hold are one camera move */
function wideCam(s) {
  const F = LY.far, S = LY.set;
  const zt = eio(inv(4.3, 5.5, s));
  const Zmax = S.w / F.w;
  const Z = Math.exp(Math.log(Zmax) * zt);
  const drift = inv(2.35, 4.3, s);
  const S0x = F.x - 22 * drift, S0y = F.y + 8 * drift;
  let Sx = lerp(S0x, S.x, zt), Sy = lerp(S0y, S.y, zt);
  const held = sstep(5.3, 6.6, s);
  Sx += held * 5 * Math.sin(TAU * s / 16); Sy += held * 4 * Math.sin(TAU * s / 12 + 1);
  const arr = s < 2.7 ? -900 * Math.pow(1 - eout(inv(2.35, 2.7, s)), 1.4) : 0;
  const hh = handheld(s, lerp(1.0, 0.42, sstep(5.2, 6.2, s)));
  return { Z, zt, Sx, Sy, arr, dx: hh.x, dy: hh.y + arr, roll: hh.r, ax: Sx, ay: Sy, px: F.x, py: F.y };
}
function screenPose(s, cam) {
  const k = cam.Z * LY.far.w / PIC.w;
  const settle = sstep(4.7, 5.9, s);
  const yaw = lerp(0.42 * Math.sin(0.9 * s + 0.4) - 0.1, -0.17 + 0.035 * Math.sin(TAU * s / 9), settle);
  const pitch = lerp(0.24 + 0.06 * Math.sin(0.7 * s), 0.06 + 0.025 * Math.sin(TAU * s / 7 + 1), settle);
  const roll = lerp(0.32 - 0.05 * s, -0.022 + 0.014 * Math.sin(TAU * s / 11), settle);
  const R = mulM(rotZ(roll), mulM(rotX(pitch), rotY(yaw)));
  const bob = settle * 4 * Math.sin(TAU * s / 6);
  return { x: cam.Sx + cam.dx, y: cam.Sy + cam.dy + bob + PIC_CY * k, k, R };
}

/* riders, idling on the frame (all periods divide 8 s) */
function riderIdle(id, s) {
  const p = ((s % 8) + 8) % 8;
  switch (id) {
    case 'A': {
      const wv = bump(1.0, 1.4, 3.4, p);
      return { stretch: 1 + 0.06 * Math.sin(s * 9.5 * 2 + 1.2) * wv + 0.02 * Math.sin(TAU * s / 4),
        armR: lerp(0.95, -1.95 + 0.5 * Math.sin(s * 9.5), wv), armL: 2.2 + 0.06 * Math.sin(TAU * s / 4),
        lookX: lerp(0.2, -0.15, wv), lookY: 0.15, pupil: 0.52, open: 1 - bump(6.3, 6.37, 6.47, p), legAmp: 0 };
    }
    case 'B': {
      const peek = bump(4.6, 5.1, 6.6, p);
      return { stretch: 1 - 0.035 * Math.sin(TAU * s / 4 + 0.6), armR: 1.05 + 0.08 * Math.sin(TAU * s / 4), armL: 2.1 - 0.08 * Math.sin(TAU * s / 4),
        lookX: lerp(-0.55, 0.05, peek), lookY: lerp(0.35, 0.05, peek), pupil: 0.5 + 0.06 * peek, open: 1 - bump(2.9, 2.97, 3.06, p) };
    }
    case 'D': {
      const kick = bump(2.0, 2.3, 3.0, p);
      return { stretch: 1.12 + 0.03 * Math.sin(TAU * s / 2), armL: -1.72 + 0.04 * Math.sin(TAU * s / 2), armR: -1.42 - 0.04 * Math.sin(TAU * s / 2),
        legPh: s * (2.2 + 9 * kick), legAmp: 0.32 + 0.8 * kick, lookX: 0.1, lookY: 0.5 - 0.3 * kick, pupil: 0.42 + 0.08 * kick, open: 1 - bump(5.5, 5.57, 5.66, p) };
    }
  }
  return {};
}
function placeOnFrame(o, r) {
  const [ux, vy] = r.at, z = 0.035;
  const a = proj(o, [ux, vy, z]), b = proj(o, [ux, vy + (r.edge === 'hang' ? -1 : 1), z]);
  const dx = b[0] - a[0], dy = b[1] - a[1], l = Math.hypot(dx, dy) || 1;
  return { x: a[0], y: a[1], nx: dx / l, ny: dy / l, up: Math.atan2(dy, dx) };
}

function drawScreen(g, base, s, cam) {
  const o = screenPose(s, cam);
  const k = o.k, lw = clamp(k * 0.016, 1.2, 4.6);
  // ribbon trail flowing away toward the upper right
  if (k > 6) {
    const flow = s * 1.6, R = k;
    const c0 = proj(o, [0.9, 0.5, 0]);
    g.lineCap = 'round';
    for (const [off, col, wk] of [[-0.18, PERI, 1], [0.16, PERI, 0.8], [0.0, CREAM, 0.55]]) {
      g.beginPath();
      for (let i = 0; i <= 40; i++) {
        const u = i / 40;
        const x = c0[0] + R * (0.2 + u * 2.2 + Math.sin(u * 3 + s * 0.6) * 0.12 + off * (1 - u) * 0.3);
        const y = c0[1] + R * (-0.15 - u * 1.25 + off * 0.6 + Math.cos(u * 2.4 + 0.5) * 0.12);
        if (i === 0) g.moveTo(x, y); else g.lineTo(x, y);
      }
      const dl = Math.max(6, R * 0.16);
      g.setLineDash([dl, dl * 0.8]); g.lineDashOffset = -flow * dl * 1.8;
      g.strokeStyle = col; g.lineWidth = Math.max(1.2, R * 0.016 * wk); g.stroke();
    }
    g.setLineDash([]);
  }
  // debris: folded scraps orbiting the screen
  const debris = [];
  for (let i = 0; i < 6; i++) {
    const ph = hash2(i, 41) * TAU, spd = 0.3 + hash2(i, 42) * 0.25, rad = 1.25 + hash2(i, 43) * 0.35;
    const a = ph + s * spd;
    debris.push({ x: o.x + Math.cos(a) * k * rad * 0.98, y: o.y - PIC_CY * k + Math.sin(a) * k * rad * 0.36, front: Math.sin(a) > 0, sz: k * (0.035 + hash2(i, 44) * 0.03), rot: s * (1 + hash2(i, 45) * 2) + ph, col: hash2(i, 46) < 0.5 ? CREAM : VERM });
  }
  const drawScrap = d => {
    if (d.sz < 1.2) return;
    g.save(); g.translate(d.x, d.y); g.rotate(d.rot);
    g.beginPath(); g.moveTo(0, -d.sz); g.lineTo(d.sz * 0.9, d.sz * 0.6); g.lineTo(-d.sz * 0.8, d.sz * 0.5); g.closePath();
    g.fillStyle = d.col; g.fill(); g.strokeStyle = PERI; g.lineWidth = Math.max(1, lw * 0.6); g.lineJoin = 'round'; g.stroke();
    g.restore();
  };
  debris.filter(d => !d.front).forEach(drawScrap);

  const riders = LY.riders.map(r => ({ r, p: placeOnFrame(o, r) }));
  const rh = k * 0.27;
  // the bezel
  const mesh = drawMesh(g, SCREEN, o, SCREEN_MAT, lw, { seed: 7 });
  const front = mulMV(o.R, [0, 0, 1])[2] > 0.04;
  if (front && k > 4) {
    const z = 0.07 + 0.003;
    // score lines around the picture, and the tape label on the bottom bezel
    const xfF = faceXf(o, [0, 0, z], [1, 0, 0], [0, -1, 0]);
    setXf(g, xfF, base);
    g.lineWidth = lw * 0.5 / k; g.strokeStyle = PERI;
    g.setLineDash([lw * 2.2 / k, lw * 1.7 / k]);
    g.strokeRect(PIC.u0 - 0.035, -PIC.v0 - 0.035, PIC.w + 0.07, PIC.h + 0.07);
    g.setLineDash([]);
    if (k > 40) {
      const lx = -0.5, ly = -(PIC.v0 - PIC.h) + 0.045, lwid = 1.0, lh = 0.11;
      g.fillStyle = CREAM; g.fillRect(lx, ly, lwid, lh);
      g.lineWidth = lw * 0.6 / k; g.strokeStyle = PERI; g.strokeRect(lx, ly, lwid, lh);
      const pitch = lh / 12.5;
      dotText(g, 'TAPE ' + st8.tape, lx + lwid * 0.07, ly + lh * 0.19, pitch, INK);
      dotText(g, TAPES[st8.tape].runtime, lx + lwid * 0.93, ly + lh * 0.19, pitch, PERI, 'right');
    }
    g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
    // the picture
    const xf = faceXf(o, [PIC.u0, PIC.v0, z], [PIC.w, 0, 0], [0, -PIC.h, 0]);
    setXf(g, xf, base);
    g.fillStyle = INK; g.fillRect(0, 0, 1, 1);
    const c = cards[st8.tape];
    const tuned = st8.tunedAt !== null ? clamp((s - st8.tunedAt) / 0.55) : 0;
    if (c && c.state && tuned > 0) {
      const since = s - st8.tunedAt;
      paintCard(c, cardClock(st8.tape, since));
      g.save(); g.globalAlpha = sstep(0, 1, tuned); g.drawImage(c.canvas, 0, 0, 1, 1); g.restore();
    }
    if (tuned < 1) drawStatic(g, s, 1 - sstep(0.2, 1, tuned), k);
    // the glass: two cream dashes of light and a thin PERI rim
    g.setTransform(base[0], base[1], base[2], base[3], base[4], base[5]);
    const gl = (u, v) => proj(o, [PIC.u0 + PIC.w * u, PIC.v0 - PIC.h * v, z]);
    if (k > 30) {
      const a1 = gl(0.06, 0.2), b1 = gl(0.15, 0.07), a2 = gl(0.05, 0.34), b2 = gl(0.08, 0.29);
      g.globalAlpha = 0.85;
      dash(g, a1[0], a1[1], b1[0], b1[1], lw * 1.1); dash(g, a2[0], a2[1], b2[0], b2[1], lw * 1.1);
      g.globalAlpha = 1;
    }
    const P4 = [gl(0, 0), gl(1, 0), gl(1, 1), gl(0, 1)];
    poly(g, P4); g.strokeStyle = PERI; g.lineWidth = lw * 0.8; g.lineJoin = 'round'; g.stroke();
    // glue tabs: unglued paper flaps on two edges
    for (const [ax, ay, bx, by, h] of [[-0.98, 0.3, -0.98, -0.1, 0.12], [0.2, 0.66, 0.62, 0.66, 0.1]]) {
      const ex = bx - ax, ey = by - ay;
      const out = ax < -0.9 ? [-1, 0] : [0, 1];
      const Q = [[ax, ay, z - 0.02], [bx, by, z - 0.02], [bx - ex * 0.12 + out[0] * h, by - ey * 0.12 + out[1] * h, z - 0.02], [ax + ex * 0.12 + out[0] * h, ay + ey * 0.12 + out[1] * h, z - 0.02]].map(v => proj(o, v));
      poly(g, Q); g.fillStyle = CREAM; g.fill();
      g.strokeStyle = PERI; g.lineWidth = lw * 0.7; g.stroke();
    }
  }
  // riders on the frame
  for (const { r, p } of riders) {
    const stR = riderIdle(r.id, s);
    if (r.edge === 'hang') {
      const fx = p.x + p.nx * rh * 1.04, fy = p.y + p.ny * rh * 1.04;
      drawRider(g, base, fx, fy, p.up + Math.PI, rh, stR);
    } else {
      drawRider(g, base, p.x, p.y, p.up, rh, stR);
    }
  }
  debris.filter(d => d.front).forEach(drawScrap);
  return { o, k, hull: mesh.hull };
}

/* static on the picture before it tunes in: dots that change every frame, a rolling band */
function drawStatic(g, s, a, k) {
  if (a <= 0.01) return;
  const fr = Math.floor(s * 18);
  g.save(); g.globalAlpha = a;
  g.fillStyle = INK; g.fillRect(0, 0, 1, 1);
  const n = Math.min(900, Math.max(60, Math.round(k * 2.2)));
  const d = 1.6 / Math.max(40, k * 1.6);
  for (let i = 0; i < n; i++) {
    const x = hash2(i, fr), y = hash2(i + 7919, fr);
    g.fillStyle = hash2(i, fr + 3) < 0.6 ? PERI : CREAM;
    g.fillRect(x, y, d * 1.8, d);
  }
  const band = ((s * 0.7) % 1.2) - 0.1;
  g.fillStyle = COBALT; g.globalAlpha = a * 0.45; g.fillRect(0, band, 1, 0.09);
  g.restore();
}

function drawWide(g, base, s) {
  const cam = wideCam(s), camPrev = wideCam(Math.max(2.35, s - 0.035));
  drawBG(g, cam, camPrev, s);
  // meteors in the wide
  for (const [t0, x0, y0, x1, y1] of LY.wide ? [[2.85, 960, 0.14, 640, 0.42], [3.6, 470, 0.08, 760, 0.25]] : [[2.85, 940, 0.1, 560, 0.3], [3.6, 120, 0.06, 470, 0.18]]) {
    const u = inv(t0, t0 + 0.32, s);
    if (u <= 0 || u >= 1) continue;
    const hx = lerp(x0, x1, eout(u)) + cam.dx * 0.8, hy = lerp(y0, y1, eout(u)) * H + cam.dy * 0.8;
    const dxm = x1 - x0, dym = (y1 - y0) * H, lm = Math.hypot(dxm, dym);
    const tl = 170 * (1 - u * 0.6);
    for (let i = 0; i < 4; i++) {
      const a0 = i * 0.3, a1 = a0 + 0.2 - i * 0.03;
      dash(g, hx - dxm / lm * tl * a0, hy - dym / lm * tl * a0, hx - dxm / lm * tl * a1, hy - dym / lm * tl * a1, 3.8 - i * 0.7);
    }
  }
  const scr = drawScreen(g, base, s, cam);
  // the robot over the shoulder; it leaves frame as we zoom
  if (cam.Z < 3.4) {
    const O = LY.over, F = LY.far;
    const Zr = Math.pow(cam.Z, 1.25);
    const bx = cam.Sx + (O.x - F.x) * Zr + cam.dx * 1.15, by = cam.Sy + (O.y - F.y) * Zr + cam.dy * 1.15;
    const m = O.mirror ? -1 : 1, mir = a => (O.mirror ? Math.PI - a : a);
    drawRobot(g, base, {
      x: bx, y: by + 9 * Math.sin(TAU * s / LOOP * 2), k: O.k * Zr,
      yaw: -0.62 * m, pitch: 0.12, roll: (0.16 + 0.03 * Math.sin(TAU * s / LOOP * 3)) * m + cam.roll,
      headYaw: 0.18 * m, headPitch: -0.22, sy: 1,
      eyes: { eyeScale: 1.04, pupil: 0.72, lookX: 0.55 * m, lookY: 0.8, open: 1 - bump(3.3, 3.36, 3.46, s), sparkle: 0 },
      earOff: [0.02 * Math.sin(s * 3), 0],
      arm: [[mir(2.2 + 0.12 * Math.sin(s * 2.2)), mir(1.7 + 0.2 * Math.sin(s * 2.2 + 0.8))], [mir(0.55 + 0.1 * Math.sin(s * 2.2 + 1.5)), mir(-0.35 + 0.18 * Math.sin(s * 2.2 + 2.3))]],
      leg: [[mir(1.95 + 0.1 * Math.sin(s * 1.7)), mir(1.75 + 0.15 * Math.sin(s * 1.7 + 0.6))], [mir(1.25 + 0.1 * Math.sin(s * 1.7 + 1.2)), mir(1.55 + 0.15 * Math.sin(s * 1.7 + 2))]],
    }, true);
  }
  return { cam, scr, Z: cam.Z };
}

/* ---------------------------------------------------------------- reticle */
function reticle(s, W, starPos) {
  if (s < 2.42) return null;
  const box = (x, y, w, h) => ({ x, y, w, h });
  const hb = bboxOf(W.scr.hull);
  const m = Math.max(16 * LY.q, (hb[2] - hb[0]) * 0.07);
  const tape = () => box((hb[0] + hb[2]) / 2, (hb[1] + hb[3]) / 2, Math.max(70 * LY.q, hb[2] - hb[0] + 2 * m), Math.max(56 * LY.q, hb[3] - hb[1] + 2 * m));
  const [fx, fy, fw, fh] = LY.full, [A, B, C] = LY.hunt.map(h => box(...h));
  const full = box(fx, fy, fw, fh);
  const S = box(starPos[0], starPos[1], 64 * LY.q, 64 * LY.q);
  const tb = tape();
  const Rel = box(lerp(starPos[0], tb.x, 0.45), lerp(starPos[1], tb.y, 0.45), 180 * LY.q, 180 * LY.q);
  const mix = (p, q, t) => box(lerp(p.x, q.x, t), lerp(p.y, q.y, t), lerp(p.w, q.w, t), lerp(p.h, q.h, t));
  if (s < 2.7) return Object.assign(mix(full, A, eout(inv(2.42, 2.7, s))), { phase: 'in' });
  if (s < 2.87) return Object.assign(A, { phase: 'hunt' });
  if (s < 3.13) return Object.assign(mix(A, B, eout(inv(2.87, 2.99, s))), { phase: 'hunt' });
  if (s < 3.31) return Object.assign(mix(B, C, eout(inv(3.13, 3.25, s))), { phase: 'hunt' });
  if (s < 3.61) return Object.assign(mix(C, S, eback(inv(3.31, 3.45, s))), { phase: 'false', blink: s > 3.45 });
  if (s < 3.83) return Object.assign(mix(S, Rel, eout(inv(3.61, 3.75, s))), { phase: 'hunt' });
  return Object.assign(mix(Rel, tb, eback(inv(3.83, 3.99, s))), { phase: 'lock' });
}

/* ---------------------------------------------------------------- overlay */
function drawOverlay(g, t, s, info) {
  const q = LY.q, ov = CREAM;
  const top = LY.headU + (LY.wide ? 14 : 4) * q;
  const L0 = LY.ov.l, R0 = 1000 - LY.ov.r;
  const f = LY.wide ? 1 : 0.82, P = 2.5 * q * f, p = 1.55 * q * f;
  // the viewfinder's frame: four faint corner marks around the camera's picture
  {
    const x0 = L0 - 14 * q, x1 = R0 + 14 * q, y0 = top - 14 * q;
    const y1 = LY.wide ? H - LY.ov.b + 10 * q : LY.set.y + 0.7225 * LY.set.w / PIC.w + 16 * q + 7 * p + 14 * q;
    const a = 16 * q;
    g.beginPath();
    g.moveTo(x0, y0 + a); g.lineTo(x0, y0); g.lineTo(x0 + a, y0);
    g.moveTo(x1 - a, y0); g.lineTo(x1, y0); g.lineTo(x1, y0 + a);
    g.moveTo(x1, y1 - a); g.lineTo(x1, y1); g.lineTo(x1 - a, y1);
    g.moveTo(x0 + a, y1); g.lineTo(x0, y1); g.lineTo(x0, y1 - a);
    g.globalAlpha = 0.5; g.lineWidth = 1.3 * q; g.strokeStyle = ov; g.lineCap = 'square'; g.stroke(); g.globalAlpha = 1;
  }
  // REC dot + timecode (counts the tape since the page opened)
  if ((t % 1) < 0.62) { g.beginPath(); g.arc(L0 + 7 * q, top + 8.5 * q, 6.5 * q, 0, TAU); g.fillStyle = VERM; g.fill(); }
  const mm = Math.floor(t / 60) % 60, ss = Math.floor(t) % 60, fr = Math.floor((t % 1) * 24);
  const tc = `00:${mm < 10 ? '0' : ''}${mm}:${ss < 10 ? '0' : ''}${ss}`;
  dotText(g, tc, L0 + 22 * q, top, P, ov);
  dotText(g, (fr < 10 ? '0' : '') + fr, L0 + 22 * q + textWidth(tc, P) + 7 * q, top + 7 * q, p, ov);
  dotText(g, 'TAPE ' + st8.tape + '/02', L0 + 22 * q, top + 26 * q, p, ov);
  // battery, last cell blinking low
  {
    const bw = 34 * q, bh = 17 * q, bx = R0 - bw - 4 * q, by = top + 0.5 * q;
    g.lineWidth = 1.8 * q; g.strokeStyle = ov; g.lineJoin = 'round';
    g.beginPath(); g.roundRect(bx, by, bw, bh, 3 * q); g.stroke();
    g.beginPath(); g.roundRect(bx + bw + 1.5 * q, by + bh * 0.3, 3 * q, bh * 0.4, 1 * q); g.fillStyle = ov; g.fill();
    const cells = 3, gap = 2 * q, cw = (bw - 5 * q - gap * (cells - 1)) / cells;
    for (let i = 0; i < cells; i++) {
      if (i === 0 && (t % 2) > 1.2) continue;
      g.beginPath(); g.roundRect(bx + 2.5 * q + i * (cw + gap), by + 2.5 * q, cw, bh - 5 * q, 1.2 * q); g.fill();
    }
  }
  // bottom right: tape mode, AF, and the tape's date stamp
  const bot = LY.wide ? H - LY.ov.b - 7 * p : LY.set.y + 0.7225 * LY.set.w / PIC.w + 16 * q;
  const date = TAPES[st8.tape].date;
  const dx = R0;
  dotText(g, date, dx, bot, p, ov, 'right');
  const afx = dx - textWidth(date, p) - 18 * q;
  if (info.af === 'solid' || (info.af === 'blink' && (t * 6 % 2) < 1.2)) {
    dotText(g, 'AF', afx, bot, p, ov, 'right');
    if (info.af === 'blink') { g.beginPath(); g.roundRect(afx - textWidth('AF', p) - 5 * q, bot - 4 * q, textWidth('AF', p) + 10 * q, 7 * p + 8 * q, 2 * q); g.strokeStyle = ov; g.lineWidth = 1.2 * q; g.stroke(); }
  }
  dotText(g, 'SP', afx - textWidth('AF', p) - 16 * q, bot, p, ov, 'right');
  // reticle
  const r = info.reticle;
  if (r) {
    const lw = 2.1 * q, arm = 24 * q;
    if (!(r.blink && (s * 16 % 2) < 1)) {
      const relock = info.relock || 0;
      const grow = 1 + 0.25 * relock;
      bracketBox(g, r.x, r.y, r.w * grow, r.h * grow, lw, arm);
      if (r.phase !== 'lock' || s < 5.7) cross(g, r.x, r.y, (r.phase === 'false' ? 7 : 11) * q, 1.6 * q);
    }
    if (r.phase === 'lock' && s > 3.91) {
      const lt = inv(3.91, 4.01, s), kk = lerp(9 * q, 0, eout(lt));
      g.beginPath();
      g.moveTo(r.x - r.w / 2 - 7 * q - kk, r.y); g.lineTo(r.x - r.w / 2 + 6 * q - kk, r.y);
      g.moveTo(r.x + r.w / 2 + 7 * q + kk, r.y); g.lineTo(r.x + r.w / 2 - 6 * q + kk, r.y);
      g.moveTo(r.x, r.y - r.h / 2 - 7 * q - kk); g.lineTo(r.x, r.y - r.h / 2 + 6 * q - kk);
      g.moveTo(r.x, r.y + r.h / 2 + 7 * q + kk); g.lineTo(r.x, r.y + r.h / 2 - 6 * q + kk);
      g.strokeStyle = ov; g.lineWidth = 1.9 * q; g.stroke();
      const label = s < 5.9 ? 'LOCK' : 'PLAY >';
      const show = s < 5.9 ? ((s * 4) % 2 < 1.4 || s > 4.5) : true;
      if (show && LY.wide) dotText(g, label, r.x + r.w / 2, r.y + r.h / 2 + 10 * q, p, ov, 'right');
      else if (show) dotText(g, label, r.x - r.w / 2, r.y + r.h / 2 + 10 * q, p, ov, 'left');
    }
  }
  // zoom bar on the right edge
  if (info.zoom && (LY.wide || s < 6.0)) {
    const x = R0 - 2 * q, y0 = LY.wide ? H * 0.34 : LY.set.y - 90 * q, y1 = LY.wide ? H * 0.62 : LY.set.y + 90 * q;
    g.strokeStyle = ov; g.lineWidth = 1.6 * q; g.lineCap = 'round';
    g.beginPath(); g.moveTo(x, y0); g.lineTo(x, y1); g.stroke();
    g.beginPath();
    for (let i = 0; i <= 8; i++) { const y = lerp(y1, y0, i / 8); const w = (i % 4 === 0 ? 7 : 4) * q; g.moveTo(x - w, y); g.lineTo(x, y); }
    g.lineWidth = 1.1 * q; g.stroke();
    dotText(g, 'T', x, y0 - 20 * q, p, ov, 'center');
    dotText(g, 'W', x, y1 + 9 * q, p, ov, 'center');
    const zmax = LY.set.w / LY.far.w;
    const zt = Math.min(1, Math.log(info.zoom) / Math.log(zmax * 1.2));
    const sy = lerp(y1, y0, zt);
    g.beginPath(); g.roundRect(x - 4.5 * q, sy - 7 * q, 9 * q, 14 * q, 2.5 * q); g.fillStyle = ov; g.fill();
    dotText(g, 'x' + info.zoom.toFixed(1), x - 13 * q, sy - 5.5 * q, p, ov, 'right');
  }
}

/* ----------------------------------------------------------------- render */
let baseXf = [1, 0, 0, 1, 0, 0];
function render(t, still) {
  const s = t;
  const g = sctx;
  g.setTransform(1, 0, 0, 1, 0, 0);
  g.fillStyle = INK; g.fillRect(0, 0, Wpx, Hpx);
  const wideShot = s >= 2.35;
  const roll = wideShot ? wideCam(s).roll : closeCam(s).roll;
  const c = Math.cos(roll), sn = Math.sin(roll);
  const cx = LY.rollC[0] * U, cy = LY.rollC[1] * U;
  baseXf = [U * c, U * sn, -U * sn, U * c, cx - (cx * c - cy * sn), cy - (cx * sn + cy * c)];
  g.setTransform(baseXf[0], baseXf[1], baseXf[2], baseXf[3], baseXf[4], baseXf[5]);
  const info = { af: 'solid', reticle: null, zoom: 0, relock: 0 };
  let blur = 0, smear = 0, smearX = 0;
  if (!wideShot) {
    drawClose(g, baseXf, s);
    smear = s > 2.12 ? 520 * Math.pow(inv(2.12, 2.35, s), 2) : 0;
  } else {
    const W = drawWide(g, baseXf, s);
    smear = s < 2.7 ? 520 * Math.pow(1 - inv(2.35, 2.7, s), 2) : 0;
    const sp = starScreen(STARS[0], wideCam(s));
    info.reticle = reticle(s, W, sp);
    info.zoom = W.Z;
    if (s > 4.55 && s < 4.95) blur = 8 * sstep(4.55, 4.95, s);
    else if (s >= 4.95 && s < 6.4) { const tau = s - 4.95; blur = Math.abs(8 * Math.exp(-4.2 * tau) * Math.cos(TAU * 2.1 * tau)); }
    if (blur < 0.25) blur = 0;
    info.af = s > 4.55 && s < 5.6 ? 'blink' : 'solid';
    if (st8.switchAt !== null) {
      const u = s - st8.switchAt;
      if (u >= 0 && u < 0.5) { smearX = 520 * bump(0, 0.16, 0.42, u); info.relock = 1 - sstep(0.18, 0.46, u); info.af = u < 0.4 ? 'blink' : 'solid'; }
    }
  }
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.fillStyle = INK; ctx.fillRect(0, 0, Wpx, Hpx);
  if (smear > 1 || smearX > 1) {
    const n = 9;
    for (let i = 0; i < n; i++) {
      const f = i / (n - 1) - 0.5;
      ctx.globalAlpha = 1 / (i + 1);
      ctx.drawImage(scene, -smearX * U * f, -smear * U * f);
    }
    ctx.globalAlpha = 1;
  } else if (blur > 0 && 'filter' in ctx) {
    ctx.filter = `blur(${(blur * U * LY.q).toFixed(2)}px)`;
    ctx.drawImage(scene, 0, 0);
    ctx.filter = 'none';
  } else ctx.drawImage(scene, 0, 0);
  const gi = still ? 0 : Math.floor(s * 12) % grains.length;
  ctx.drawImage(grains[gi], 0, 0, Wpx, Hpx);
  ctx.setTransform(U, 0, 0, U, 0, 0);
  drawOverlay(ctx, t, s, info);
}

/* ----------------------------------------------------------------- layout */
const section = cv.closest('[data-opening]');
function layout() {
  const r = section.getBoundingClientRect();
  const cw = Math.max(320, r.width), ch = Math.max(420, r.height);
  DPR = Math.min(2, window.devicePixelRatio || 1);
  // keep the full-page canvas affordable: about 4.2 MP at most
  const cap = Math.sqrt(4.2e6 / (cw * ch));
  if (DPR > cap) DPR = Math.max(1, cap);
  cv.style.width = cw + 'px'; cv.style.height = ch + 'px';
  Wpx = Math.round(cw * DPR); Hpx = Math.round(ch * DPR);
  cv.width = Wpx; cv.height = Hpx; scene.width = Wpx; scene.height = Hpx;
  U = Wpx / 1000; H = Hpx / U;
  LY = computeLayout(cw, ch);
  LY.botPad = 0;
  STARS[0].x = LY.star[0]; STARS[0].y = LY.star[1];
  buildFarTex();
  buildGrain();
  for (const k in cards) delete cards[k];
  cardFor(st8.tape);
}

/* -------------------------------------------------------------------- run */
const qs = new URLSearchParams(location.search);
const fixedT = qs.has('t') ? parseFloat(qs.get('t')) : null;
if (qs.get('tape') === '01') st8.tape = '01';
const reduce = matchMedia('(prefers-reduced-motion: reduce)');
// someone who watched the intro in the last 12 hours lands straight on the hold
let seen = false;
try { seen = Date.now() - Number(localStorage.getItem('pr-opening-seen') || 0) < 12 * 3600e3; } catch (e) { /* storage may be blocked */ }
const skipIntro = qs.has('settled') || (fixedT === null && seen);
let t0 = performance.now() - (skipIntro ? (T_SET + 0.2) * 1000 : 0);
let raf = 0, paused = false, pausedAt = 0, onScreen = true, lastFrame = 0;
let resolveReady; window.OPENING_READY = new Promise(r => { resolveReady = r; });
window.__openingReady = false;

function now() { return (performance.now() - t0) / 1000; }
function lockedUI(t) {
  section.classList.toggle('is-locked', t >= 5.35);
  section.classList.toggle('is-intro', t < T_SET);
  if (t >= T_SET && !lockedUI.saved) { lockedUI.saved = true; try { localStorage.setItem('pr-opening-seen', String(Date.now())); } catch (e) { /* ignore */ } }
}
function tuneIfReady(t) {
  if (st8.tunedAt !== null) return;
  const c = cardFor(st8.tape);
  if (!c || !c.state) return;
  if (st8.switchAt !== null) { if (t - st8.switchAt > 0.22) st8.tunedAt = t; }
  else if (t >= 5.15) st8.tunedAt = Math.max(5.15, t);
}
function tick(ts) {
  raf = 0;
  if (paused || !onScreen || document.hidden) return;
  const t = now();
  // build the playing card in slices; later the other tape, then let the rest of the page draw
  const c = cardFor(st8.tape);
  const done = stepCard(c, t < 5.6 ? 9 : 6);
  if (done) {
    resolveReady();
    const other = cardFor(ORDER.find(n => n !== st8.tape));
    if (t > 7) stepCard(other, 4);
  }
  tuneIfReady(t);
  // the hold runs at about 30 fps; the intro at full rate
  if (t < T_SET + 0.6 || ts - lastFrame > 32) { render(t, false); lastFrame = ts; }
  lockedUI(t);
  raf = requestAnimationFrame(tick);
}
function drawStill(t) {
  const c = cardFor(st8.tape);
  buildCardNow(c);
  if (st8.tunedAt === null) st8.tunedAt = Math.min(5.15, t);
  render(t, true);
  lockedUI(t);
  resolveReady();
  window.__openingReady = true;
}
function start() {
  cancelAnimationFrame(raf); raf = 0;
  if (fixedT !== null && !isNaN(fixedT)) {
    const c = cardFor(st8.tape);
    if (fixedT >= 5.15) { buildCardNow(c); st8.tunedAt = qs.has('tuned') ? fixedT - parseFloat(qs.get('tuned')) : 5.15; }
    render(fixedT, false); lockedUI(fixedT);
    resolveReady(); window.__openingReady = true;
    // review hook for recordings: draw any moment of the shot without reloading
    window.__renderAt = tt => {
      if (tt >= 5.15) { buildCardNow(cardFor(st8.tape)); if (st8.tunedAt === null) st8.tunedAt = 5.15; }
      render(tt, false); lockedUI(tt);
    };
    return;
  }
  if (reduce.matches) { const c = cardFor(st8.tape); buildCardNow(c); st8.tunedAt = 7.2 - (TAPES[st8.tape].reveal + 1.2); drawStill(7.2); return; }
  raf = requestAnimationFrame(tick);
}

/* page controls: skip, pause, tape selector */
const ctl = {
  skip: section.querySelector('[data-skip]'),
  motion: section.querySelector('[data-motion]'),
  tapes: [...section.querySelectorAll('[data-tape]')],
};
function setPaused(p) {
  if (p === paused) return;
  paused = p;
  if (p) { pausedAt = performance.now(); cancelAnimationFrame(raf); raf = 0; }
  else { t0 += performance.now() - pausedAt; raf = requestAnimationFrame(tick); }
  if (ctl.motion) { ctl.motion.setAttribute('aria-pressed', String(p)); ctl.motion.textContent = p ? 'Play motion' : 'Pause motion'; }
}
ctl.skip?.addEventListener('click', () => {
  const t = now();
  if (t < T_SET) { t0 = performance.now() - (T_SET + 0.2) * 1000; if (paused) setPaused(false); }
  else { t0 = performance.now(); st8.tunedAt = null; st8.switchAt = null; if (paused) setPaused(false); }
  ctl.skip.blur();
});
ctl.motion?.addEventListener('click', () => setPaused(!paused));
function switchTape(n) {
  if (n === st8.tape || !TAPES[n]) return;
  const t = fixedT !== null ? fixedT : now();
  st8.prevTape = st8.tape; st8.tape = n;
  if (t < T_SET) t0 = performance.now() - (T_SET + 0.2) * 1000;
  st8.switchAt = fixedT !== null ? fixedT : now();
  st8.tunedAt = null;
  const c = cardFor(n);
  if (reduce.matches || paused) { buildCardNow(c); st8.switchAt = null; const ts = Math.max(7.2, t); st8.tunedAt = ts - (TAPES[n].reveal + 1.2); render(ts, true); }
  else stepCard(c, 0);
  for (const b of ctl.tapes) b.setAttribute('aria-pressed', String(b.dataset.tape === n));
  section.dispatchEvent(new CustomEvent('tapechange', { detail: { tape: n } }));
}
for (const b of ctl.tapes) b.addEventListener('click', () => switchTape(b.dataset.tape));

// only animate while the opening is on screen and the tab is visible
new IntersectionObserver(es => {
  for (const e of es) { onScreen = e.isIntersecting; if (onScreen && !raf && !paused && fixedT === null && !reduce.matches) raf = requestAnimationFrame(tick); }
}).observe(section);
document.addEventListener('visibilitychange', () => {
  if (fixedT !== null || reduce.matches || paused) return;
  if (document.hidden) { cancelAnimationFrame(raf); raf = 0; pausedAt = performance.now(); }
  else { t0 += performance.now() - pausedAt; if (!raf) raf = requestAnimationFrame(tick); }
});
reduce.addEventListener?.('change', start);
let rt = 0;
addEventListener('resize', () => { clearTimeout(rt); rt = setTimeout(() => { layout(); start(); }, 160); });

async function boot() {
  try { await Promise.race([document.fonts.ready, new Promise(r => setTimeout(r, 1500))]); } catch (e) { /* fall back */ }
  layout();
  if (st8.tape !== '02') for (const b of ctl.tapes) b.setAttribute('aria-pressed', String(b.dataset.tape === st8.tape));
  if (st8.tape !== '02') section.dispatchEvent(new CustomEvent('tapechange', { detail: { tape: st8.tape } }));
  start();
}
boot();
window.OPENING = { switchTape, setPaused };

})();
