import { esc } from './layout.mjs';
import { films } from '../data/films.mjs';
const scenes = [
 { ...films[0], preview:'/assets/films/capricious-god/previews/the-palace-8s.mp4', poster:'/assets/films/capricious-god/the-palace.webp', short:'The Hugging Face incident', line:'An AI agent has one job. Please its god.', genre:'AI safety · An animated allegory' },
 { ...films[1], preview:'/assets/films/robotics-revolution/previews/robotics-8s.mp4', poster:'/assets/films/robotics-revolution/previews/robotics-poster.webp', posterAlt:'A human and a blue robot look toward a painted city, with birds flying overhead.', short:'When AI gets a body', line:'One model. A world full of hands.', genre:'Robotics · An animated essay' },
];
export function cinemaHero() {
 return `<section class="cinema-hero" aria-labelledby="cinema-title" data-cinema><div class="cinema-scenes">${scenes.map((film,i)=>`<div class="cinema-scene${i===0?' is-current':''}" data-scene="${i}" ${i?'aria-hidden="true"':''}><img src="${film.poster}" alt="" width="1440" height="810" ${i?'loading="lazy"':'fetchpriority="high"'}><video muted loop playsinline preload="none" data-preview="${film.preview}" aria-hidden="true"></video></div>`).join('')}</div><div class="cinema-shade"></div><div class="cinema-intro"><span class="cinema-kicker">Animated films about AI & possible futures</span><h1 id="cinema-title">Paper<br><em>Robots.</em></h1><p>Stories from the other<br>side of the machine.</p><a href="#library" class="cinema-explore">Explore the films <span aria-hidden="true">↓</span></a></div><div class="cinema-feature">${scenes.map((film,i)=>`<article class="cinema-feature-copy" data-feature="${i}" data-film-id="${film.id}" data-film-title="${esc(film.title)}" ${i?'hidden':''}><span>Film ${film.number} / ${film.genre}</span><h2>${film.line}</h2><p>${film.short}<br><small>${film.title}</small></p><a href="${film.page}" class="cinema-play" data-cinema-play><b aria-hidden="true">▶</b><span>Watch the film<small>${film.duration} · By San Kala</small></span></a><a href="${film.page}" class="cinema-details">${i?'Essay & film notes':'The story, script & sources'} ↗</a></article>`).join('')}</div><div class="cinema-bottom"><div class="cinema-selector" role="group" aria-label="Choose a film preview" hidden>${scenes.map((film,i)=>`<button type="button" data-select-scene="${i}" aria-pressed="${i===0}"><span>${film.number}</span><strong>${film.short}</strong><i aria-hidden="true">↗</i></button>`).join('')}</div><button type="button" class="cinema-motion" data-motion hidden>Pause motion <span aria-hidden="true">Ⅱ</span></button></div></section><dialog class="cinema-screen" aria-label="Watch a Paper Robots film"><div class="cinema-screen-bar"><span data-screen-title></span><button type="button" data-close-screen>Close film ×</button></div><div class="cinema-screen-player"></div><a data-screen-youtube href="${'https://www.youtube.com/watch?v='+scenes[0].id}">Open on YouTube ↗</a></dialog>`;
}
export function cinemaCollection() {
 return `<section class="cinema-collection shell" id="library" aria-labelledby="films-heading"><div class="cinema-section-title"><span>The collection / 2026</span><h2 id="films-heading">The films<span>02</span></h2></div><div class="cinema-posters">${scenes.map(film=>`<article data-film-entry><a href="${film.page}" class="cinema-poster"><img src="${film.poster}" alt="${esc(film.posterAlt || film.cardAlt || film.alt)}" width="1440" height="810" loading="lazy"><span class="poster-number">${film.number}</span><span class="poster-open">Enter the film ↗</span></a><div class="poster-caption"><span>${film.genre} / ${film.duration}</span><h3><a href="${film.page}">${film.title}</a></h3><p>${film.description}</p><a href="${film.page}">Watch & explore ↗</a></div></article>`).join('')}</div></section>`;
}
