import site from '../../site.config.mjs';
export const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const arrow = '<span aria-hidden="true">↗</span>';
export const action = (href,label,quiet=false) => `<a class="action${quiet ? ' quiet' : ''}" href="${esc(href)}">${label} ${arrow}</a>`;
const navItems = [['/essays/','Essays'],['/films/','Films'],['/about/','About'],['/follow/','Follow']];
// Follow copy, shared by the Follow page and the homepage. YouTube and RSS only
// until a verified Substack publication origin is set in site.config.mjs.
export const follow = {
  eyebrow: 'More from Paper Robots',
  title: ['Follow the films.', 'Stay for the ideas.'],
  lede: site.substack ? 'Get the complete essays in your inbox. Free to read, at the pace the ideas take.' : 'Follow Paper Robots on YouTube for the films, or add the essays to your feed reader.',
  primary: site.substack ? [site.substack + '/subscribe', 'Read & subscribe on Substack'] : [site.youtube, 'Follow on YouTube'],
};
export function followSection() {
  return `<section class="follow-section shell" id="follow"><div><span class="eyebrow">${follow.eyebrow}</span><h2>${follow.title[0]}<br><em>${follow.title[1]}</em></h2><p>${follow.lede}</p>${action(...follow.primary)}</div><aside><span class="eyebrow">Prefer to read?</span><h3>The writing<br>behind the films.</h3><p>The essays have the space for sources and arguments. The films are another way into the same ideas.</p><div class="follow-links"><a href="/essays/">Browse the essays ${arrow}</a><a href="${site.youtube}">Watch on YouTube ${arrow}</a><a href="/feed.xml">Follow by RSS ${arrow}</a></div></aside></section>`;
}
// head: page-specific styles, data and scripts. mark: the wordmark's picture
// (the painted robot by default; the homepage draws its head in code).
const paintedMark = '<img src="/assets/identity/paper-robot.webp" alt="" width="46" height="46">';
export function layout({title,description=site.description,path='/',content,canonical,image='/assets/identity/social-cover.jpg',type='website',schema,noindex=false,webAnalytics=false,head='',bodyClass='',mark=paintedMark,after='',themeColor='#f9f3e7'}) {
  // Vercel serves this endpoint; local builds and the Pages fallback omit it.
  const analytics = webAnalytics ? '<script>window.va = window.va || function () { (window.vaq = window.vaq || []).push(arguments); };</script><script defer src="/_vercel/insights/script.js"></script>' : '';
  const links = navItems.map(([href,label])=>`<a href="${href}"${path.startsWith(href) ? ' aria-current="page"' : ''}>${label}</a>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="theme-color" content="${themeColor}"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical || site.url + path}">${noindex ? '<meta name="robots" content="noindex">' : ''}<meta property="og:site_name" content="Paper Robots"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site.url + path}"><meta property="og:image" content="${site.url + image}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${site.url + image}"><link rel="icon" href="/assets/identity/paper-robot.webp" type="image/webp"><link rel="alternate" type="application/rss+xml" title="Paper Robots" href="/feed.xml"><link rel="stylesheet" href="/styles/site.css"><link rel="stylesheet" href="/styles/publication.css"><link rel="stylesheet" href="/styles/studio.css"><script defer src="/scripts/site.js"></script>${head}${schema ? `<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>` : ''}${analytics}</head><body class="brand-paper${bodyClass ? ' ' + bodyClass : ''}"><a class="skip" href="#main">Skip to content</a><header class="site-header shell"><a class="wordmark" href="/">${mark}Paper Robots<span class="wordmark-dot">.</span></a><nav class="desktop-nav" aria-label="Main">${links}</nav><details class="mobile-menu"><summary>Menu +</summary><nav aria-label="Mobile">${links}</nav></details></header>${content}<footer class="site-footer shell"><div><strong>Paper Robots</strong><p>AI, robots & possible futures.<br>Essays and films by San Kala.</p></div><nav aria-label="Footer"><a href="${site.authorUrl}/">About the author ${arrow}</a><a href="${site.youtube}">YouTube ${arrow}</a>${site.substack ? `<a href="${site.substack}">Substack ${arrow}</a>` : ''}<a href="/feed.xml">RSS ${arrow}</a><a href="mailto:san@sankala.me">Get in touch ${arrow}</a></nav><small>Free to read and watch.</small></footer>${after}</body></html>`;
}
