#!/bin/sh
# Assemble js/opening.js: the evidence loop's drawing kit (copied unchanged from
# sankala.me design/prototypes/2026-10-code-drawn-art/evidence-loop) plus the new
# opening, inside one function scope so it can sit beside the film kits' globals.
cd "$(dirname "$0")/js" || exit 1
{
  printf "/* opening.js — generated by ../build.sh from _evidence-parts.js and _opening-core.js. Edit those. */\n(function () {\n'use strict';\n"
  cat _evidence-parts.js
  printf "\n\n"
  cat _opening-core.js
  printf "\n})();\n"
} > opening.js
node --check opening.js && echo "opening.js ok ($(wc -l < opening.js) lines)"
